const doctorData = [
    {
      id: "1",
      name: "ডা. লামিয়া হক",
      degree: "এমবিবিএস, এফসিপিএস",
      specialty: "নিউরোলজিস্ট",
      experience: "11+ years",
      bmdc_number: "A25765",
      rating: "4.5 (1655)",
      hospital: "সরকারি হাসপাতাল, ঢাকা",
      consultation_fee: "৳600 (incl. VAT)",
      follow_up_fee: "৳300 (within 14 days)",
      languages: "বাংলা, ইংরেজি",
      consultation_time: {
        instant: "শনিবার - বৃহস্পতিবার (৩টা - ৯টা)",
        appointment: "রবিবার (১০টা - ১২টা)",
      },
      patients_attended: "4314+",
      avg_consultation_time: "11 minutes",
      joined_date: "2020-08-16",
      doctor_code: "DT7403",
      profile_image: "https://i.ibb.co.com/S4wvgcNw/Leonardo-Phoenix-10-A-professional-profile-image-of-a-Banglade-2-1.jpg",
    },
    {
      id: "2",
      name: "ডা. রুবাইয়া সুলতানা",
      degree: "এমবিবিএস, এমএস",
      specialty: "ইএনটি বিশেষজ্ঞ",
      experience: "10+ years",
      bmdc_number: "B79669",
      rating: "4.7 (1868)",
      hospital: "সরকারি হাসপাতাল, ঢাকা",
      consultation_fee: "৳500 (incl. VAT)",
      follow_up_fee: "৳200 (within 14 days)",
      languages: "বাংলা, ইংরেজি",
      consultation_time: {
        instant: "শনিবার - বৃহস্পতিবার (৩টা - ৯টা)",
        appointment: "রবিবার (১০টা - ১২টা)",
      },
      patients_attended: "6988+",
      avg_consultation_time: "19 minutes",
      joined_date: "2021-12-22",
      doctor_code: "DT8428",
      profile_image: "https://i.ibb.co.com/S4wvgcNw/Leonardo-Phoenix-10-A-professional-profile-image-of-a-Banglade-2-1.jpg",
    },
    {
      id: "3",
      name: "ডা. ফারজানা কবির",
      degree: "এমবিবিএস, এমএস",
      specialty: "গাইনিকোলজিস্ট",
      experience: "14+ years",
      bmdc_number: "C23573",
      rating: "4.6 (1079)",
      hospital: "সরকারি হাসপাতাল, ঢাকা",
      consultation_fee: "৳500 (incl. VAT)",
      follow_up_fee: "৳300 (within 14 days)",
      languages: "বাংলা, ইংরেজি",
      consultation_time: {
        instant: "শনিবার - বৃহস্পতিবার (৩টা - ৯টা)",
        appointment: "রবিবার (১০টা - ১২টা)",
      },
      patients_attended: "7040+",
      avg_consultation_time: "18 minutes",
      joined_date: "2021-01-18",
      doctor_code: "DT5733",
      profile_image: "https://i.ibb.co.com/mCMytgX8/Leonardo-Phoenix-10-A-professional-profile-image-of-a-Banglade-3-1.jpg",
    },
    {
      id: "4",
      name: "ডা. তানজিলা রহমান",
      degree: "এমবিবিএস, এফসিপিএস",
      specialty: "চাইল্ড স্পেশালিস্ট",
      experience: "14+ years",
      bmdc_number: "D44006",
      rating: "4.6 (1171)",
      hospital: "সরকারি হাসপাতাল, ঢাকা",
      consultation_fee: "৳400 (incl. VAT)",
      follow_up_fee: "৳300 (within 14 days)",
      languages: "বাংলা, ইংরেজি",
      consultation_time: {
        instant: "শনিবার - বৃহস্পতিবার (৩টা - ৯টা)",
        appointment: "রবিবার (১০টা - ১২টা)",
      },
      patients_attended: "7224+",
      avg_consultation_time: "12 minutes",
      joined_date: "2022-09-17",
      doctor_code: "DT8783",
      profile_image: "https://i.ibb.co.com/N28Wr2gK/Leonardo-Phoenix-10-A-professional-profile-image-of-a-Banglade-0.jpg",
    },
    {
      id: "5",
      name: "ডা. শারমিন আক্তার",
      degree: "এমবিবিএস, এফসিপিএস",
      specialty: "ডার্মাটোলজিস্ট",
      experience: "15+ years",
      bmdc_number: "E79628",
      rating: "4.8 (1067)",
      hospital: "সরকারি হাসপাতাল, ঢাকা",
      consultation_fee: "৳600 (incl. VAT)",
      follow_up_fee: "৳300 (within 14 days)",
      languages: "বাংলা, ইংরেজি",
      consultation_time: {
        instant: "শনিবার - বৃহস্পতিবার (৩টা - ৯টা)",
        appointment: "রবিবার (১০টা - ১২টা)",
      },
      patients_attended: "7201+",
      avg_consultation_time: "20 minutes",
      joined_date: "2021-12-26",
      doctor_code: "DT5409",
      profile_image: "https://i.ibb.co.com/pBKphb73/Leonardo-Phoenix-10-A-professional-profile-image-of-a-Banglade-1-1.jpg",
    },
    {
      id: "6",
      name: "ডা. সাবিহা আলম",
      degree: "এমবিবিএস, এমডি",
      specialty: "কার্ডিওলজিস্ট",
      experience: "7+ years",
      bmdc_number: "F38016",
      rating: "4.8 (1064)",
      hospital: "সরকারি হাসপাতাল, ঢাকা",
      consultation_fee: "৳700 (incl. VAT)",
      follow_up_fee: "৳350 (within 14 days)",
      languages: "বাংলা, ইংরেজি",
      consultation_time: {
        instant: "শনিবার - বৃহস্পতিবার (৩টা - ৯টা)",
        appointment: "রবিবার (১০টা - ১২টা)",
      },
      patients_attended: "6610+",
      avg_consultation_time: "14 minutes",
      joined_date: "2020-01-20",
      doctor_code: "DT6547",
      profile_image: "https://i.ibb.co.com/N28Wr2gK/Leonardo-Phoenix-10-A-professional-profile-image-of-a-Banglade-0.jpg",
    },
    {
      id: "7",
      name: "ডা. মাহিরা খন্দকার",
      degree: "এমবিবিএস, এমফিল",
      specialty: "পেডিয়াট্রিশিয়ান",
      experience: "8+ years",
      bmdc_number: "G86313",
      rating: "4.5 (1300)",
      hospital: "সরকারি হাসপাতাল, ঢাকা",
      consultation_fee: "৳600 (incl. VAT)",
      follow_up_fee: "৳250 (within 14 days)",
      languages: "বাংলা, ইংরেজি",
      consultation_time: {
        instant: "শনিবার - বৃহস্পতিবার (৩টা - ৯টা)",
        appointment: "রবিবার (১০টা - ১২টা)",
      },
      patients_attended: "4728+",
      avg_consultation_time: "12 minutes",
      joined_date: "2020-04-03",
      doctor_code: "DT5825",
      profile_image: "https://i.ibb.co.com/N28Wr2gK/Leonardo-Phoenix-10-A-professional-profile-image-of-a-Banglade-0.jpg",
    },
    {
      id: "8",
      name: "ডা. সুমাইয়া জামান",
      degree: "এমবিবিএস, এমএস",
      specialty: "এন্ডোক্রিনোলজিস্ট",
      experience: "6+ years",
      bmdc_number: "H13565",
      rating: "5.0 (1935)",
      hospital: "সরকারি হাসপাতাল, ঢাকা",
      consultation_fee: "৳600 (incl. VAT)",
      follow_up_fee: "৳200 (within 14 days)",
      languages: "বাংলা, ইংরেজি",
      consultation_time: {
        instant: "শনিবার - বৃহস্পতিবার (৩টা - ৯টা)",
        appointment: "রবিবার (১০টা - ১২টা)",
      },
      patients_attended: "6418+",
      avg_consultation_time: "14 minutes",
      joined_date: "2020-04-12",
      doctor_code: "DT9092",
      profile_image: "https://i.ibb.co.com/N28Wr2gK/Leonardo-Phoenix-10-A-professional-profile-image-of-a-Banglade-0.jpg",
    },
    {
      id: "9",
      name: "ডা. ফারিয়া হাসান",
      degree: "এমবিবিএস, এমডি",
      specialty: "নেফ্রোলজিস্ট",
      experience: "14+ years",
      bmdc_number: "I79527",
      rating: "4.8 (1231)",
      hospital: "সরকারি হাসপাতাল, ঢাকা",
      consultation_fee: "৳600 (incl. VAT)",
      follow_up_fee: "৳300 (within 14 days)",
      languages: "বাংলা, ইংরেজি",
      consultation_time: {
        instant: "শনিবার - বৃহস্পতিবার (৩টা - ৯টা)",
        appointment: "রবিবার (১০টা - ১২টা)",
      },
      patients_attended: "4805+",
      avg_consultation_time: "16 minutes",
      joined_date: "2020-06-02",
      doctor_code: "DT4756",
      profile_image: "https://i.ibb.co.com/kVYcvKyx/Leonardo-Phoenix-10-A-professional-profile-image-of-a-Banglade-3.jpg",
    },
    {
      id: "10",
      name: "ডা. নুসরাত জাহান",
      degree: "এমবিবিএস, এমফিল",
      specialty: "জেনারেল ফিজিশিয়ান",
      experience: "7+ years",
      bmdc_number: "J47543",
      rating: "4.7 (1258)",
      hospital: "সরকারি হাসপাতাল, ঢাকা",
      consultation_fee: "৳700 (incl. VAT)",
      follow_up_fee: "৳250 (within 14 days)",
      languages: "বাংলা, ইংরেজি",
      consultation_time: {
        instant: "শনিবার - বৃহস্পতিবার (৩টা - ৯টা)",
        appointment: "রবিবার (১০টা - ১২টা)",
      },
      patients_attended: "7944+",
      avg_consultation_time: "16 minutes",
      joined_date: "2021-07-18",
      doctor_code: "DT4139",
      profile_image: "https://i.ibb.co.com/YFHdsmbF/Leonardo-Phoenix-10-A-professional-profile-image-of-a-Banglade-2.jpg",
    },
  ];
  
  export default doctorData;
  