const hospitalData = [
  {
    appointmentId: "APPT-20231027-001",
    hospital: {
      hospitalId: "HOSP-001",
      hospitalName: "সিটি জেনারেল হাসপাতাল",
      address: "১০ হাসপাতাল রোড, যেকোনো শহর",
      contactNumber: "৫৫৫-১০০-২০০০",
      imageUrl:
        "https://i.ibb.co.com/ym6QDhww/Gemini-Generated-Image-a31u5na31u5na31u.jpg",
      website: "www.citygeneralhospital.com", // Added website address
    },
    doctor: {
      doctorId: "DR-67890",
      firstName: "রবার্ট",
      lastName: "স্মিথ",
      specialization: "কার্ডিওলজি",
    },
    appointmentDate: "২০২৩-১১-১৫",
    appointmentTime: "১০:০০",
    location: "কার্ডিওলজি ক্লিনিক, ২য় তলা",
    reasonForVisit: "ফলো-আপ চেকআপ",
    notes: "সাম্প্রতিক রক্ত পরীক্ষার ফলাফল আনুন।",
    fees: {
      amount: 1500,
      currency: "BDT",
    },
    paymentStatus: "Paid",
  },
  {
    appointmentId: "APPT-20231027-002",
    hospital: {
      hospitalId: "HOSP-002",
      hospitalName: "আঞ্চলিক মেডিকেল সেন্টার",
      address: "২৫ মেডিকেল এভিনিউ, যেকোনো শহর",
      contactNumber: "৫৫৫-২০০-৩০০০",
      imageUrl:
        "https://i.ibb.co.com/9HxGn3C1/Gemini-Generated-Image-tdpa5etdpa5etdpa.jpg",
      website: "www.regionalmedicalcenter.com", // Added website address
    },
    doctor: {
      doctorId: "DR-13579",
      firstName: "এমিলি",
      lastName: "ডেভিস",
      specialization: "ডার্মাটোলজি",
    },
    appointmentDate: "২০২৩-১১-১৬",
    appointmentTime: "১৪:৩০",
    location: "ডার্মাটোলজি ক্লিনিক, ৩য় তলা",
    reasonForVisit: "ত্বকের ফুসকুড়ি মূল্যায়ন",
    notes: "অ্যাপয়েন্টমেন্টের আগে লোশন বা ক্রিম লাগানো এড়িয়ে চলুন।",
    fees: {
      amount: 2000,
      currency: "BDT",
    },
    paymentStatus: "Pending",
  },
  {
    appointmentId: "APPT-20231027-003",
    hospital: {
      hospitalId: "HOSP-003",
      hospitalName: "সেন্ট লুকস হাসপাতাল",
      address: "৪০ চার্চ স্ট্রিট, যেকোনো শহর",
      contactNumber: "৫৫৫-৩০০-৪০০০",
      imageUrl:
        "https://i.ibb.co.com/MD6vQsts/Gemini-Generated-Image-4gg28v4gg28v4gg2.jpg",
      website: "www.stlukeshospital.com", // Added website address
    },
    doctor: {
      doctorId: "DR-24680",
      firstName: "মাইকেল",
      lastName: "উইলসন",
      specialization: "পেডিয়াট্রিক্স",
    },
    appointmentDate: "২০২৩-১১-১৭",
    appointmentTime: "০৯:১৫",
    location: "পেডিয়াট্রিক্স ক্লিনিক, ১ম তলা",
    reasonForVisit: "বার্ষিক চেকআপ",
    notes: "টিকা দেওয়ার রেকর্ড আনুন।",
    fees: {
      amount: 1200,
      currency: "BDT",
    },
    paymentStatus: "Paid",
  },
  {
    appointmentId: "APPT-20231027-004",
    hospital: {
      hospitalId: "HOSP-004",
      hospitalName: "কমিউনিটি হেলথ ক্লিনিক",
      address: "১৫ মেইন স্ট্রিট, যেকোনো শহর",
      contactNumber: "৫৫৫-৪০০-৫০০০",
      imageUrl:
        "https://i.ibb.co.com/B5xk6KBB/Gemini-Generated-Image-e7cpye7cpye7cpye.jpg",
      website: "www.communityhealthclinic.org", // Added website address
    },
    doctor: {
      doctorId: "DR-98765",
      firstName: "জেসিকা",
      lastName: "মুর",
      specialization: "অর্থোপেডিক্স",
    },
    appointmentDate: "২০২৩-১১-১৮",
    appointmentTime: "১১:০০",
    location: "অর্থোপেডিক্স ক্লিনিক, ৪র্থ তলা",
    reasonForVisit: "হাঁটু ব্যথার মূল্যায়ন",
    notes: "আরামদায়ক পোশাক পরুন।",
    fees: {
      amount: 2500,
      currency: "BDT",
    },
    paymentStatus: "Partially Paid",
  },
  {
    appointmentId: "APPT-20231027-005",
    hospital: {
      hospitalId: "HOSP-005",
      hospitalName: "স্পেশালিটি সার্জিক্যাল সেন্টার",
      address: "৩০ সার্জিক্যাল ড্রাইভ, যেকোনো শহর",
      contactNumber: "৫৫৫-৫০০-৬০০০",
      imageUrl:
        "https://i.ibb.co.com/4wTp4Jvr/Gemini-Generated-Image-aa1y5aaa1y5aaa1y.jpg",
      website: "www.specialtysurgicalcenter.com", // Added website address
    },
    doctor: {
      doctorId: "DR-36912",
      firstName: "ডেভিড",
      lastName: "টেইলর",
      specialization: "নিউরোলোজি",
    },
    appointmentDate: "২০২৩-১১-১৯",
    appointmentTime: "১৫:৪৫",
    location: "নিউরোলোজি ক্লিনিক, ৫ম তলা",
    reasonForVisit: "মাইগ্রেন মূল্যায়ন",
    notes: "সাম্প্রতিক মাথাব্যথার একটি লগ রাখুন।",
    fees: {
      amount: 3000,
      currency: "BDT",
    },
    paymentStatus: "Not Paid",
  },
  {
    appointmentId: "APPT-20231028-006",
    hospital: {
      hospitalId: "HOSP-001",
      hospitalName: "সিটি জেনারেল হাসপাতাল",
      address: "১০ হাসপাতাল রোড, যেকোনো শহর",
      contactNumber: "৫৫৫-১০০-২০০০",
      imageUrl:
        "https://i.ibb.co.com/ym6QDhww/Gemini-Generated-Image-a31u5na31u5na31u.jpg",
      website: "www.citygeneralhospital.com", // Added website address
    },
    doctor: {
      doctorId: "DR-11223",
      firstName: "সোফিয়া",
      lastName: "রহমান",
      specialization: "গাইনোকোলজি",
    },
    appointmentDate: "২০২৩-১১-২০",
    appointmentTime: "১২:০০",
    location: "গাইনোকোলজি ক্লিনিক, ৬ষ্ঠ তলা",
    reasonForVisit: "প্রসবপূর্ব চেকআপ",
    notes: "আল্ট্রাসাউন্ড রিপোর্ট আনুন।",
    fees: {
      amount: 2800,
      currency: "BDT",
    },
    paymentStatus: "Paid",
  },
  {
    appointmentId: "APPT-20231028-007",
    hospital: {
      hospitalId: "HOSP-002",
      hospitalName: "আঞ্চলিক মেডিকেল সেন্টার",
      address: "২৫ মেডিকেল এভিনিউ, যেকোনো শহর",
      contactNumber: "৫৫৫-২০০-৩০০০",
      imageUrl:
        "https://i.ibb.co.com/9HxGn3C1/Gemini-Generated-Image-tdpa5etdpa5etdpa.jpg",
      website: "www.regionalmedicalcenter.com", // Added website address
    },
    doctor: {
      doctorId: "DR-44556",
      firstName: "আরিফ",
      lastName: "হোসেন",
      specialization: "ইউরোলজি",
    },
    appointmentDate: "২০২৩-১১-২১",
    appointmentTime: "১৪:৪৫",
    location: "ইউরোলজি ক্লিনিক, ৭ম তলা",
    reasonForVisit: "কিডনি স্টোন চেকআপ",
    notes: "রক্ত ও ইউরিন টেস্ট রিপোর্ট আনুন।",
    fees: {
      amount: 3200,
      currency: "BDT",
    },
    paymentStatus: "Pending",
  },
  {
    appointmentId: "APPT-20231028-008",
    hospital: {
      hospitalId: "HOSP-003",
      hospitalName: "সেন্ট লুকস হাসপাতাল",
      address: "৪০ চার্চ স্ট্রিট, যেকোনো শহর",
      contactNumber: "৫৫৫-৩০০-৪০০০",
      imageUrl:
        "https://i.ibb.co.com/MD6vQsts/Gemini-Generated-Image-4gg28v4gg28v4gg2.jpg",
      website: "www.stlukeshospital.com", // Added website address
    },
    doctor: {
      doctorId: "DR-77889",
      firstName: "ফারজানা",
      lastName: "আক্তার",
      specialization: "অপথালমোলজি",
    },
    appointmentDate: "২০২৩-১১-২২",
    appointmentTime: "১০:৩০",
    location: "অপথালমোলজি ক্লিনিক, ৮ম তলা",
    reasonForVisit: "চোখের সাধারণ চেকআপ",
    notes: "চোখের চশমার প্রেসক্রিপশন আনুন।",
    fees: {
      amount: 1800,
      currency: "BDT",
    },
    paymentStatus: "Paid",
  },
  {
    appointmentId: "APPT-20231028-009",
    hospital: {
      hospitalId: "HOSP-004",
      hospitalName: "কমিউনিটি হেলথ ক্লিনিক",
      address: "১৫ মেইন স্ট্রিট, যেকোনো শহর",
      contactNumber: "৫৫৫-৪০০-৫০০০",
      imageUrl:
        "https://i.ibb.co.com/B5xk6KBB/Gemini-Generated-Image-e7cpye7cpye7cpye.jpg",
      website: "www.communityhealthclinic.org", // Added website address
    },
    doctor: {
      doctorId: "DR-99001",
      firstName: "ইমরান",
      lastName: "কবির",
      specialization: "ইএনটি",
    },
    appointmentDate: "২০২৩-১১-২৩",
    appointmentTime: "১১:৪৫",
    location: "ইএনটি ক্লিনিক, ৯ম তলা",
    reasonForVisit: "নাক ও গলার সমস্যা",
    notes: "পূর্বের কোনো টেস্ট রিপোর্ট থাকলে আনুন।",
    fees: {
      amount: 2200,
      currency: "BDT",
    },
    paymentStatus: "Partially Paid",
  },
  {
    appointmentId: "APPT-20231028-010",
    hospital: {
      hospitalId: "HOSP-005",
      hospitalName: "স্পেশালিটি সার্জিক্যাল সেন্টার",
      address: "৩০ সার্জিক্যাল ড্রাইভ, যেকোনো শহর",
      contactNumber: "৫৫৫-৫০০-৬০০০",
      imageUrl:
        "https://i.ibb.co.com/4wTp4Jvr/Gemini-Generated-Image-aa1y5aaa1y5aaa1y.jpg",
      website: "www.specialtysurgicalcenter.com", // Added website address
    },
    doctor: {
      doctorId: "DR-22334",
      firstName: "সাদিয়া",
      lastName: "আহমেদ",
      specialization: "প্লাস্টিক সার্জারি",
    },
    appointmentDate: "২০২৩-১১-২৪",
    appointmentTime: "১৫:৩০",
    location: "প্লাস্টিক সার্জারি ক্লিনিক, ১০ম তলা",
    reasonForVisit: "পোড়া দাগের চিকিৎসা",
    notes: "পূর্বের চিকিৎসার ছবি আনুন।",
    fees: {
      amount: 3500,
      currency: "BDT",
    },
    paymentStatus: "Not Paid",
  },
];

const medicineData = [
  {
    id: "med001",
    name: "Paracetamol 500mg",
    brand: "ACME Pharma",
    category: "Pain Reliever",
    price: "30",
    discount: "5",
    stock: "100",
    expiry_date: "2026-01-15",
    description: "Paracetamol is widely used for relieving mild to moderate pain, such as headaches, toothaches, and muscle aches. It also reduces fever. It is commonly found in households and is safe for all ages when used correctly.",
    prescription_required: "false",
    image: "https://i.ibb.co.com/jPMr51ms/Leonardo-Phoenix-10-Create-a-highquality-product-image-of-a-me-0-2.jpg"
  },
  {
    id: "med002",
    name: "Azithromycin 250mg",
    brand: "Square Pharmaceuticals",
    category: "Antibiotic",
    price: "120",
    discount: "10",
    stock: "50",
    expiry_date: "2025-12-01",
    description: "Azithromycin is a macrolide antibiotic effective in treating various bacterial infections including respiratory tract infections, skin infections, and sexually transmitted diseases. It’s often used in a short course dosage.",
    prescription_required: "true",
    image: "https://i.ibb.co.com/WWQ1SN64/Leonardo-Phoenix-10-Create-a-highquality-product-image-of-a-me-0-1.jpg"
  },
  {
    id: "med003",
    name: "Cetirizine 10mg",
    brand: "Renata Limited",
    category: "Antihistamine",
    price: "20",
    discount: "0",
    stock: "200",
    expiry_date: "2026-06-30",
    description: "Cetirizine is an antihistamine used to relieve allergy symptoms such as watery eyes, runny nose, itching eyes/nose, and sneezing. It is non-drowsy and provides 24-hour relief.",
    prescription_required: "false",
    image: "https://i.ibb.co.com/7xcFc89w/Leonardo-Phoenix-10-Create-a-highquality-product-image-of-a-me-1-1.jpg"
  },
  {
    id: "med004",
    name: "Omeprazole 20mg",
    brand: "Beximco Pharma",
    category: "Antacid",
    price: "50",
    discount: "8",
    stock: "80",
    expiry_date: "2025-10-20",
    description: "Omeprazole is a proton pump inhibitor (PPI) that reduces stomach acid. It is used to treat conditions like GERD, ulcers, and heartburn. It provides long-lasting relief from acid reflux symptoms.",
    prescription_required: "false",
    image: "https://i.ibb.co.com/0jrhbqbZ/Leonardo-Phoenix-10-Create-a-highquality-product-image-of-a-me-2-1.jpg"
  },
  {
    id: "med005",
    name: "Metformin 500mg",
    brand: "Eskayef Pharmaceuticals",
    category: "Diabetes",
    price: "60",
    discount: "5",
    stock: "70",
    expiry_date: "2026-02-28",
    description: "Metformin is an oral diabetes medicine that helps control blood sugar levels. It is commonly used to manage type 2 diabetes and is often the first medication prescribed for this condition.",
    prescription_required: "true",
    image: "https://i.ibb.co.com/0R96qgTj/Leonardo-Phoenix-10-Create-a-highquality-product-image-of-a-me-3-1.jpg"
  },
  {
    id: "med006",
    name: "Amlodipine 5mg",
    brand: "Incepta Pharmaceuticals",
    category: "Blood Pressure",
    price: "40",
    discount: "5",
    stock: "90",
    expiry_date: "2025-09-01",
    description: "Amlodipine is a calcium channel blocker used to treat high blood pressure and angina (chest pain). It helps prevent strokes, heart attacks, and kidney problems by relaxing blood vessels.",
    prescription_required: "true",
    image: "https://i.ibb.co.com/Zzc89KDw/Leonardo-Phoenix-10-Create-a-highquality-product-image-of-a-me-3.jpg"
  },
  {
    id: "med007",
    name: "Losartan 50mg",
    brand: "ACI Limited",
    category: "Blood Pressure",
    price: "45",
    discount: "3",
    stock: "60",
    expiry_date: "2026-01-01",
    description: "Losartan is an angiotensin receptor blocker (ARB) used to treat high blood pressure and to protect the kidneys from damage due to diabetes. It also lowers the risk of strokes in patients with high blood pressure and heart disease.",
    prescription_required: "true",
    image: "https://i.ibb.co.com/NMFz4KJ/Leonardo-Phoenix-10-Create-a-highquality-product-image-of-a-me-2.jpg"
  },
  {
    id: "med008",
    name: "Montelukast 10mg",
    brand: "Healthcare Pharmaceuticals",
    category: "Asthma",
    price: "55",
    discount: "7",
    stock: "100",
    expiry_date: "2026-03-10",
    description: "Montelukast is used to prevent wheezing, difficulty breathing, chest tightness, and coughing caused by asthma. It is also effective in treating seasonal allergies. It works by blocking substances that cause inflammation.",
    prescription_required: "false",
    image: "https://i.ibb.co.com/zT9Ckhf6/Leonardo-Phoenix-10-Create-a-highquality-product-image-of-a-me-1.jpg"
  },
  {
    id: "med009",
    name: "Loratadine 10mg",
    brand: "Opsonin Pharma",
    category: "Antihistamine",
    price: "18",
    discount: "0",
    stock: "150",
    expiry_date: "2026-07-01",
    description: "Loratadine is a long-acting antihistamine that helps relieve symptoms of allergies such as sneezing, runny nose, and itchy eyes. It is non-drowsy and often used during allergy seasons.",
    prescription_required: "false",
    image: "https://i.ibb.co.com/PG3K5hbG/Leonardo-Phoenix-10-Create-a-highquality-product-image-of-a-me-0.jpg"
  },
  {
    id: "med010",
    name: "Rabeprazole 20mg",
    brand: "Beximco Pharma",
    category: "Antacid",
    price: "52",
    discount: "5",
    stock: "75",
    expiry_date: "2025-11-25",
    description: "Rabeprazole belongs to the class of proton pump inhibitors (PPIs). It reduces stomach acid and is used to treat conditions like GERD, Zollinger-Ellison syndrome, and ulcers. Provides fast and long-term relief.",
    prescription_required: "false",
    image: "https://i.ibb.co.com/MxknkzC6/Leonardo-Phoenix-10-Create-a-highquality-product-image-of-a-me-3-4.jpg"
  },
  // The remaining medicines (med011 to med040) will follow...
];


// const clothingData = [
//   {
//     id: "wc001",
//     name: "ফ্লোরাল প্রিন্টেড ম্যাক্সি ড্রেস",
//     brand: "আরঙ",
//     category: "ড্রেস",
//     price: 1850,
//     discount: 10,
//     stock: 50,
//     size: ["S", "M", "L"],
//     color: "লাল",
//     material: "কটন",
//     description: "আরামদায়ক গ্রীষ্মকালীন ম্যাক্সি ড্রেস।",
//     image: "https://i.ibb.co.com/CpXqvdwg/66c5ba00966d7-square.jpg",
//   },
//   {
//     id: "wc002",
//     name: "লং কামিজ",
//     brand: "ইয়েলো",
//     category: "কামিজ",
//     price: 1450,
//     discount: 5,
//     stock: 30,
//     size: ["M", "L", "XL"],
//     color: "সবুজ",
//     material: "লিনেন",
//     description: "দৈনন্দিন ব্যবহারের জন্য উপযোগী।",
//     image: "https://i.ibb.co.com/FPL8B1D/640031abaefc9-square.jpg",
//   },
//   {
//     id: "wc003",
//     name: "সিল্ক শাড়ি",
//     brand: "বিবিয়ানা",
//     category: "শাড়ি",
//     price: 3200,
//     discount: 12,
//     stock: 20,
//     size: ["Free Size"],
//     color: "বেগুনি",
//     material: "সিল্ক",
//     description: "উৎসবের জন্য উপযুক্ত চকচকে শাড়ি।",
//     image: "https://i.ibb.co.com/FLXFJP3k/65e2a6914a266-square.jpg",
//   },
//   {
//     id: "wc004",
//     name: "ডেনিম জিন্স",
//     brand: "ইজিলাইফ",
//     category: "জিন্স",
//     price: 1300,
//     discount: 7,
//     stock: 40,
//     size: ["28", "30", "32"],
//     color: "নীল",
//     material: "ডেনিম",
//     description: "দীর্ঘস্থায়ী ও ট্রেন্ডি জিন্স।",
//     image: "https://i.ibb.co.com/CpXqvdwg/66c5ba00966d7-square.jpg",
//   },
//   {
//     id: "wc005",
//     name: "উইন্টার সোয়েটার",
//     brand: "টেক্সমার্ট",
//     category: "উইন্টার",
//     price: 1650,
//     discount: 8,
//     stock: 25,
//     size: ["S", "M", "L"],
//     color: "ধূসর",
//     material: "উল",
//     description: "শীতে উষ্ণতা ও স্টাইলের জন্য।",
//     image: "https://i.ibb.co.com/FPL8B1D/640031abaefc9-square.jpg",
//   },
//   {
//     id: "wc006",
//     name: "পালাজ্জো প্যান্ট",
//     brand: "জয়িতা",
//     category: "বটম",
//     price: 900,
//     discount: 5,
//     stock: 60,
//     size: ["M", "L", "XL"],
//     color: "কালো",
//     material: "ভিসকোস",
//     description: "হালকা আরামদায়ক দৈনন্দিন পোশাক।",
//     image: "https://i.ibb.co.com/FLXFJP3k/65e2a6914a266-square.jpg",
//   },
//   {
//     id: "wc007",
//     name: "এমব্রয়ডার কুর্তি",
//     brand: "ইয়েলো",
//     category: "কুর্তি",
//     price: 1250,
//     discount: 6,
//     stock: 35,
//     size: ["S", "M", "L"],
//     color: "হলুদ",
//     material: "কটন",
//     description: "এমব্রয়ডারি নকশা সহ আকর্ষণীয় কুর্তি।",
//     image: "https://i.ibb.co.com/CpXqvdwg/66c5ba00966d7-square.jpg",
//   },
//   {
//     id: "wc008",
//     name: "লং স্কার্ট",
//     brand: "আরঙ",
//     category: "স্কার্ট",
//     price: 1150,
//     discount: 4,
//     stock: 45,
//     size: ["Free Size"],
//     color: "লাল",
//     material: "জর্জেট",
//     description: "নারীসুলভ ও ফ্যাশনেবল স্কার্ট।",
//     image: "https://i.ibb.co.com/FPL8B1D/640031abaefc9-square.jpg",
//   },
//   {
//     id: "wc009",
//     name: "কারিগরি কাজের কামিজ",
//     brand: "বিবিয়ানা",
//     category: "কামিজ",
//     price: 1950,
//     discount: 9,
//     stock: 30,
//     size: ["M", "L"],
//     color: "বেগুনি ও সোনালী",
//     material: "সিল্ক-কটন মিশ্রণ",
//     description: "বিয়ের অনুষ্ঠান বা গেট টুগেদারের জন্য।",
//     image: "https://i.ibb.co.com/FLXFJP3k/65e2a6914a266-square.jpg",
//   },
//   {
//     id: "wc010",
//     name: "ফরমাল ব্লাউজ",
//     brand: "ইজিলাইফ",
//     category: "টপস",
//     price: 850,
//     discount: 5,
//     stock: 55,
//     size: ["S", "M", "L"],
//     color: "সাদা",
//     material: "সাটিন",
//     description: "অফিস বা প্রেজেন্টেশন উপযোগী ব্লাউজ।",
//     image: "https://i.ibb.co.com/CpXqvdwg/66c5ba00966d7-square.jpg",
//   },
//   {
//     id: "wc011",
//     name: "টিউনিক টপ",
//     brand: "ইয়েলো",
//     category: "টপস",
//     price: 990,
//     discount: 6,
//     stock: 35,
//     size: ["M", "L"],
//     color: "পিচ",
//     material: "জর্জেট",
//     description: "বহুমুখী ব্যবহারের জন্য আকর্ষণীয় টিউনিক।",
//     image: "https://i.ibb.co.com/FPL8B1D/640031abaefc9-square.jpg",
//   },
//   {
//     id: "wc012",
//     name: "চিকন কটন কামিজ",
//     brand: "টেক্সমার্ট",
//     category: "কামিজ",
//     price: 1180,
//     discount: 5,
//     stock: 40,
//     size: ["S", "M"],
//     color: "সাদা ও নীল প্রিন্ট",
//     material: "কটন",
//     description: "দীর্ঘ সময় পরে আরামদায়ক।",
//     image: "https://i.ibb.co.com/FLXFJP3k/65e2a6914a266-square.jpg",
//   },
//   {
//     id: "wc013",
//     name: "ব্রোকেড শাড়ি",
//     brand: "আরঙ",
//     category: "শাড়ি",
//     price: 2800,
//     discount: 10,
//     stock: 22,
//     size: ["Free Size"],
//     color: "মেরুন",
//     material: "ব্রোকেড",
//     description: "ঐতিহ্যবাহী ও স্টাইলিশ শাড়ি।",
//     image: "https://i.ibb.co.com/CpXqvdwg/66c5ba00966d7-square.jpg",
//   },
//   {
//     id: "wc014",
//     name: "কাজ করা কোট",
//     brand: "ইজিলাইফ",
//     category: "উইন্টার",
//     price: 2200,
//     discount: 12,
//     stock: 18,
//     size: ["M", "L"],
//     color: "কফি",
//     material: "উল",
//     description: "শীতে ফ্যাশনের সাথে উষ্ণতা।",
//     image: "https://i.ibb.co.com/FPL8B1D/640031abaefc9-square.jpg",
//   },
//   {
//     id: "wc015",
//     name: "ফুল হাতা গাউন",
//     brand: "বিবিয়ানা",
//     category: "গাউন",
//     price: 2750,
//     discount: 15,
//     stock: 20,
//     size: ["M", "L", "XL"],
//     color: "বেগুনি",
//     material: "সাটিন",
//     description: "রাত্রিকালীন বা ইভনিং প্রোগ্রামের জন্য।",
//     image: "https://i.ibb.co.com/FLXFJP3k/65e2a6914a266-square.jpg",
//   },
//   {
//     id: "wc016",
//     name: "শর্ট টপ",
//     brand: "জয়িতা",
//     category: "টপস",
//     price: 780,
//     discount: 3,
//     stock: 65,
//     size: ["S", "M"],
//     color: "লাল ও কালো",
//     material: "কটন",
//     description: "ক্যাজুয়াল পোশাকের জন্য উপযোগী।",
//     image: "https://i.ibb.co.com/CpXqvdwg/66c5ba00966d7-square.jpg",
//   },
//   {
//     id: "wc017",
//     name: "লং কামিজ উইথ ওড়না",
//     brand: "আরঙ",
//     category: "থ্রি-পিস",
//     price: 2250,
//     discount: 7,
//     stock: 30,
//     size: ["M", "L", "XL"],
//     color: "লাল ও সাদা",
//     material: "লিনেন",
//     description: "পুরো সেটসহ স্টাইলিশ লুক।",
//     image: "https://i.ibb.co.com/FPL8B1D/640031abaefc9-square.jpg",
//   },
//   {
//     id: "wc018",
//     name: "স্মার্ট কটন শার্ট",
//     brand: "ইয়েলো",
//     category: "শার্ট",
//     price: 980,
//     discount: 4,
//     stock: 38,
//     size: ["S", "M", "L"],
//     color: "ব্লু স্ট্রাইপ",
//     material: "কটন",
//     description: "আরামদায়ক ও ক্যাজুয়াল লুকের জন্য।",
//     image: "https://i.ibb.co.com/FLXFJP3k/65e2a6914a266-square.jpg",
//   },
//   {
//     id: "wc019",
//     name: "পার্টি গাউন",
//     brand: "টেক্সমার্ট",
//     category: "গাউন",
//     price: 2950,
//     discount: 13,
//     stock: 15,
//     size: ["M", "L"],
//     color: "গোলাপী",
//     material: "সিল্ক",
//     description: "পার্টি বা বিশেষ অনুষ্ঠানের জন্য।",
//     image: "https://i.ibb.co.com/CpXqvdwg/66c5ba00966d7-square.jpg",
//   },
//   {
//     id: "wc020",
//     name: "কটন সালোয়ার কামিজ",
//     brand: "বিবিয়ানা",
//     category: "থ্রি-পিস",
//     price: 1890,
//     discount: 6,
//     stock: 40,
//     size: ["S", "M", "L", "XL"],
//     color: "সবুজ",
//     material: "কটন",
//     description: "আরামদায়ক দৈনন্দিন ব্যবহার।",
//     image: "https://i.ibb.co.com/FPL8B1D/640031abaefc9-square.jpg",
//   },
// ];
const clothingData = [
  {
    id: "wc001",
    name: "ফ্লোরাল প্রিন্টেড ম্যাক্সি ড্রেস",
    brand: "আরঙ",
    category: "ড্রেস",
    price: 1850,
    discount: 10,
    stock: 50,
    size: ["S", "M", "L"],
    color: "লাল",
    material: "কটন",
    description: "নরম কটন কাপড়ে তৈরি এই ম্যাক্সি ড্রেসটি গ্রীষ্মকালের জন্য অত্যন্ত আরামদায়ক। ফুলেল প্রিন্ট ও ঢিলেঢালা কাটিং একে করে তুলেছে আধুনিক ও আকর্ষণীয়। এটি ঘুরতে যাওয়া, পার্টি বা নিত্যদিনের ব্যবহারে উপযোগী।",
    care: "হালকা ডিটারজেন্টে হাত ধুয়ে শুকাতে হবে ছায়ায়।",
    fabricQuality: "১০০% ব্রেথেবল কটন",
    usage: "ডে-টাইম বা আউটিং ড্রেস",
    image: "https://i.ibb.co.com/CpXqvdwg/66c5ba00966d7-square.jpg"
  },
  {
    id: "wc002",
    name: "লং কামিজ",
    brand: "ইয়েলো",
    category: "কামিজ",
    price: 1450,
    discount: 5,
    stock: 30,
    size: ["M", "L", "XL"],
    color: "সবুজ",
    material: "লিনেন",
    description: "এই লং কামিজটি তৈরি করা হয়েছে উন্নত মানের লিনেন কাপড়ে, যা শরীরকে রাখে ঠান্ডা ও আরামদায়ক। ক্লাসিক ডিজাইন এবং আরামদায়ক ফিটিংয়ের কারণে এটি দৈনন্দিন ব্যবহার বা অফিসের জন্য একদম উপযুক্ত।",
    care: "মেশিন ওয়াশ উপযোগী, ঠান্ডা পানিতে ধুতে হবে।",
    fabricQuality: "লাইটওয়েট ও সফট লিনেন",
    usage: "ডেইলি ও অফিস ওয়্যার",
    image: "https://i.ibb.co.com/FPL8B1D/640031abaefc9-square.jpg"
  },
  {
    id: "wc003",
    name: "সিল্ক শাড়ি",
    brand: "বিবিয়ানা",
    category: "শাড়ি",
    price: 3200,
    discount: 12,
    stock: 20,
    size: ["Free Size"],
    color: "বেগুনি",
    material: "সিল্ক",
    description: "চকমকে সিল্কের তৈরি এই শাড়িটি উৎসব বা বিবাহ অনুষ্ঠানের জন্য উপযুক্ত। বেগুনি রঙের রুচিশীলতা এবং মসৃণ টেক্সচারের মিশেলে তৈরি এটি আধুনিক নারীর জন্য পারফেক্ট চয়েস।",
    care: "ড্রাই ক্লিন রেকমেন্ডেড।",
    fabricQuality: "ফাইন কোয়ালিটি সিল্ক",
    usage: "উৎসব, বিয়ে, স্পেশাল ইভেন্ট",
    image: "https://i.ibb.co.com/FLXFJP3k/65e2a6914a266-square.jpg"
  },
  {
    id: "wc004",
    name: "ডেনিম জিন্স",
    brand: "ইজিলাইফ",
    category: "জিন্স",
    price: 1300,
    discount: 7,
    stock: 40,
    size: ["28", "30", "32"],
    color: "নীল",
    material: "ডেনিম",
    description: "দীর্ঘস্থায়ী ও স্টাইলিশ এই ডেনিম জিন্সটি প্রতিদিনের ব্যবহারে পারফেক্ট। এতে রয়েছে স্লিম ফিট কাটিং, যা আপনার লুককে করে তুলবে আরও আকর্ষণীয়।",
    care: "ঠান্ডা পানিতে উল্টে ধোয়া ভালো।",
    fabricQuality: "হেভি ওয়াশ ডেনিম",
    usage: "ক্যাজুয়াল ডে ওয়্যার",
    image: "https://i.ibb.co.com/CpXqvdwg/66c5ba00966d7-square.jpg"
  },
  {
    id: "wc005",
    name: "উইন্টার সোয়েটার",
    brand: "টেক্সমার্ট",
    category: "উইন্টার",
    price: 1650,
    discount: 8,
    stock: 25,
    size: ["S", "M", "L"],
    color: "ধূসর",
    material: "উল",
    description: "উচ্চ মানের উল থেকে তৈরি এই সোয়েটারটি শীতকালে উষ্ণতা নিশ্চিত করে। ধূসর রঙের ক্লাসিক লুক ও সফট টেক্সচারের কারণে এটি স্টাইল ও আরাম দুটোই বজায় রাখে।",
    care: "ড্রাই ক্লিন প্রেফারেবল, হ্যান্ড ওয়াশও চলবে।",
    fabricQuality: "সফট উল ব্লেন্ড",
    usage: "শীতকালীন আউটার",
    image: "https://i.ibb.co.com/FPL8B1D/640031abaefc9-square.jpg"
  },
  // Add similar enhancements for other items...
];

const websiteData = [
  {
    serviceName: "বেসিক ওয়েবসাইট",
    description: "একটি রেসপনসিভ সিঙ্গেল পেজ ওয়েবসাইট, কনট্যাক্ট ফর্ম সহ।",
    price: "৳১০০",
    deliveryTime: "৩ দিন",
    revisions: "২ বার",
    extras: ["এসইও অপটিমাইজেশন", "সোশ্যাল মিডিয়া ইন্টিগ্রেশন"],
    image: "https://i.ibb.co.com/p60dGDNv/impact-img.png",
  },
  {
    serviceName: "বিজনেস ওয়েবসাইট",
    description: "একাধিক পেজ সহ ডাইনামিক কনটেন্ট ও বেসিক অ্যানিমেশনস।",
    price: "৳৩০০",
    deliveryTime: "৫ দিন",
    revisions: "৩ বার",
    extras: ["কাস্টম অ্যাডমিন প্যানেল", "ব্লগ সেটআপ"],
    image: "https://i.ibb.co.com/1hRphf2/select-dealer-case.png",
  },
  {
    serviceName: "ই-কমার্স ওয়েবসাইট",
    description:
      "প্রোডাক্ট লিস্টিং, শপিং কার্ট ও পেমেন্ট গেটওয়ে সহ অনলাইন স্টোর।",
    price: "৳৬০০",
    deliveryTime: "৭ দিন",
    revisions: "৪ বার",
    extras: ["ইনভেন্টরি ম্যানেজমেন্ট", "কুপন সিস্টেম", "ইউজার অ্যাকাউন্ট"],
    image: "https://i.ibb.co.com/Nn3K6YNV/alhussaini.png",
  },
  {
    serviceName: "বেসিক ওয়েবসাইট",
    description: "একটি রেসপনসিভ সিঙ্গেল পেজ ওয়েবসাইট, কনট্যাক্ট ফর্ম সহ।",
    price: "৳১০০",
    deliveryTime: "৩ দিন",
    revisions: "২ বার",
    extras: ["এসইও অপটিমাইজেশন", "সোশ্যাল মিডিয়া ইন্টিগ্রেশন"],
    image: "https://i.ibb.co.com/p60dGDNv/impact-img.png",
  },
  {
    serviceName: "বিজনেস ওয়েবসাইট",
    description: "একাধিক পেজ সহ ডাইনামিক কনটেন্ট ও বেসিক অ্যানিমেশনস।",
    price: "৳৩০০",
    deliveryTime: "৫ দিন",
    revisions: "৩ বার",
    extras: ["কাস্টম অ্যাডমিন প্যানেল", "ব্লগ সেটআপ"],
    image: "https://i.ibb.co.com/1hRphf2/select-dealer-case.png",
  },
  {
    serviceName: "ই-কমার্স ওয়েবসাইট",
    description:
      "প্রোডাক্ট লিস্টিং, শপিং কার্ট ও পেমেন্ট গেটওয়ে সহ অনলাইন স্টোর।",
    price: "৳৬০০",
    deliveryTime: "৭ দিন",
    revisions: "৪ বার",
    extras: ["ইনভেন্টরি ম্যানেজমেন্ট", "কুপন সিস্টেম", "ইউজার অ্যাকাউন্ট"],
    image: "https://i.ibb.co.com/Nn3K6YNV/alhussaini.png",
  },
  {
    serviceName: "ল্যান্ডিং পেজ",
    description: "মার্কেটিং ক্যাম্পেইনের জন্য কনভার্শন-ফোকাসড ল্যান্ডিং পেজ।",
    price: "৳৮০",
    deliveryTime: "২ দিন",
    revisions: "১ বার",
    extras: ["অ্যানালিটিক্স ইন্টিগ্রেশন", "নিউজলেটার সাবস্ক্রিপশন"],
    image: "https://i.ibb.co.com/p60dGDNv/impact-img.png",
  },
  {
    serviceName: "পোর্টফোলিও ওয়েবসাইট",
    description: "ডেভেলপার/ডিজাইনারের জন্য পার্সোনাল ব্র্যান্ডিং ওয়েবসাইট।",
    price: "৳২০০",
    deliveryTime: "৪ দিন",
    revisions: "২ বার",
    extras: ["প্রজেক্ট গ্যালারি", "কন্টাক্ট ফর্ম"],
    image: "https://i.ibb.co.com/1hRphf2/select-dealer-case.png",
  },
  {
    serviceName: "এডভান্সড ওয়েব অ্যাপ্লিকেশন",
    description: "কমপ্লেক্স ফিচার সহ কাস্টম ওয়েব অ্যাপ, ইউজার বেসড।",
    price: "৳১০০০",
    deliveryTime: "১০ দিন",
    revisions: "৫ বার",
    extras: [
      "রোল বেইসড ইউজার সিস্টেম",
      "রিয়েল-টাইম ডেটা আপডেট",
      "এপিআই ইন্টিগ্রেশন",
    ],
    image: "https://i.ibb.co.com/Nn3K6YNV/alhussaini.png",
  },
];

const mobileAppData = [
  {
    serviceName: "বেসিক মোবাইল অ্যাপ",
    description: "সাধারণ ইউআই সহ একটি বেসিক মোবাইল অ্যাপ অ্যান্ড্রয়েডের জন্য।",
    price: "৳১৫০",
    deliveryTime: "৩ দিন",
    revisions: "২ বার",
    extras: ["পুশ নোটিফিকেশন", "ফায়ারবেস ইন্টিগ্রেশন"],
    image: "https://i.ibb.co.com/VpcQgpk9/2.png",
  },
  {
    serviceName: "বিজনেস অ্যাপ",
    description:
      "বিজনেস ফিচার সহ একটি প্রফেশনাল অ্যাপ, অর্ডার এবং চ্যাট সাপোর্ট সহ।",
    price: "৳৪০০",
    deliveryTime: "৫ দিন",
    revisions: "৩ বার",
    extras: ["চ্যাট সাপোর্ট", "লোকেশন সার্ভিস"],
    image: "https://i.ibb.co.com/HTq9dXGs/1.png",
  },
  {
    serviceName: "ই-কমার্স অ্যাপ",
    description:
      "অনলাইন শপের জন্য সম্পূর্ণ ফিচারড ই-কমার্স অ্যাপ, পেমেন্ট গেটওয়ে সহ।",
    price: "৳৭০০",
    deliveryTime: "৭ দিন",
    revisions: "৪ বার",
    extras: ["পেমেন্ট ইন্টিগ্রেশন", "ইনভেন্টরি কন্ট্রোল", "ইউজার প্রোফাইল"],
    image: "https://i.ibb.co.com/nqwvZqkf/3.png",
  },
  {
    serviceName: "লাইটওয়েট অ্যাপ",
    description: "ছোট বা স্পেসিফিক ফাংশনালিটির জন্য হালকা মোবাইল অ্যাপ।",
    price: "৳১২০",
    deliveryTime: "২ দিন",
    revisions: "১ বার",
    extras: ["কুইক পারফরম্যান্স", "অফলাইন সাপোর্ট"],
    image: "https://i.ibb.co.com/VpcQgpk9/2.png",
  },
  {
    serviceName: "পোর্টফোলিও অ্যাপ",
    description: "পার্সোনাল ব্র্যান্ডিং বা কাজের প্রদর্শনের জন্য মোবাইল অ্যাপ।",
    price: "৳২০০",
    deliveryTime: "৪ দিন",
    revisions: "২ বার",
    extras: ["ইন্টারঅ্যাকটিভ ইউআই", "কন্টাক্ট ফর্ম"],
    image: "https://i.ibb.co.com/HTq9dXGs/1.png",
  },
  {
    serviceName: "এডভান্সড হাইব্রিড অ্যাপ",
    description:
      "React Native বা Flutter ব্যবহার করে অ্যান্ড্রয়েড ও iOS এর জন্য অ্যাপ।",
    price: "৳১২০০",
    deliveryTime: "১০ দিন",
    revisions: "৫ বার",
    extras: [
      "ক্রস-প্ল্যাটফর্ম সাপোর্ট",
      "রিয়েল-টাইম ডেটা",
      "এক্সটারনাল এপিআই",
    ],
    image: "https://i.ibb.co.com/nqwvZqkf/3.png",
  },
];

const beautyProducts = [
  {
    id: 1,
    name: "ম্যাট লিপস্টিক",
    brand: "ল্যাকমে",
    category: "লিপস্টিক",
    shade: "রোজ পিংক",
    price: 299,
    discount: 10,
    stock: 50,
    description: "ল্যাকমে ম্যাট লিপস্টিক আপনার ঠোঁটে এনে দেবে নিখুঁত রঙ ও মসৃণতা। এই রোজ পিংক শেডটি ন্যাচারাল এবং এলিগেন্ট, যা যেকোনো সময়ের জন্য উপযুক্ত। এটি দীর্ঘস্থায়ী এবং ওয়াটারপ্রুফ হওয়ায় বারবার রি-টাচ করার প্রয়োজন পড়ে না।",
    image: "https://i.ibb.co.com/VW2w2FrX/Leonardo-Phoenix-10-A-closeup-product-photo-of-a-matte-lipstic-3.jpg"
  },
  {
    id: 2,
    name: "ফাউন্ডেশন SPF 25",
    brand: "মেবেলিন",
    category: "ফাউন্ডেশন",
    shade: "ন্যাচারাল বিঞ্জ",
    price: 599,
    discount: 15,
    stock: 30,
    description: "মেবেলিনের এই ফাউন্ডেশনটি হালকা থেকে মিডিয়াম কভারেজ দিয়ে থাকে এবং মুখের দাগ-ছোপ ঢেকে রাখে। SPF 25 থাকার কারণে এটি সূর্যের ক্ষতিকর রশ্মি থেকে সুরক্ষা দেয়। ন্যাচারাল বিঞ্জ শেডটি অধিকাংশ ত্বকের সাথে মানানসই।",
    image: "https://i.ibb.co.com/VW2w2FrX/Leonardo-Phoenix-10-A-closeup-product-photo-of-a-matte-lipstic-3.jpg"
  },
  {
    id: 3,
    name: "স্মাজ-প্রুফ কাজল",
    brand: "লরিয়াল",
    category: "কাজল",
    shade: "ব্ল্যাক ম্যাজিক",
    price: 199,
    discount: 5,
    stock: 100,
    description: "লরিয়াল ব্ল্যাক ম্যাজিক কাজলটি চোখের সৌন্দর্য বাড়ায় এক গাঢ় কালো রেখা দিয়ে। এটি স্মাজ-প্রুফ ও ওয়াটারপ্রুফ হওয়ায় দীর্ঘ সময় পরেও চোখে একইভাবে টিকে থাকে। ব্যবহার করা সহজ এবং সংবেদনশীল চোখের জন্যও নিরাপদ।",
    image: "https://i.ibb.co.com/VW2w2FrX/Leonardo-Phoenix-10-A-closeup-product-photo-of-a-matte-lipstic-3.jpg"
  },
  {
    id: 4,
    name: "প্রেসড পাউডার",
    brand: "কলরবার",
    category: "পাউডার",
    shade: "স্যান্ড বেইজ",
    price: 275,
    discount: 10,
    stock: 60,
    description: "স্যান্ড বেইজ শেডের এই প্রেসড পাউডারটি ত্বকে দেয় ন্যাচারাল ও সফট লুক। এটি মুখের অতিরিক্ত তেল কমিয়ে একটি ম্যাট ফিনিশ দেয়। অ্যালার্জি-টেস্টেড ও অয়েল-ফ্রি হওয়ায় প্রতিদিনের ব্যবহারে আদর্শ।",
    image: "https://i.ibb.co.com/VW2w2FrX/Leonardo-Phoenix-10-A-closeup-product-photo-of-a-matte-lipstic-3.jpg"
  },
  {
    id: 5,
    name: "টিন্টেড লিপ বাম",
    brand: "হিমালয়া",
    category: "লিপ কেয়ার",
    shade: "চেরি গ্লো",
    price: 99,
    discount: 5,
    stock: 90,
    description: "হিমালয়া টিন্টেড লিপ বাম চেরি গ্লো শেডে আসে যা ঠোঁটে হালকা লাল আভা দেয়। এটি প্রাকৃতিক উপাদানে তৈরি, ঠোঁট ময়েশ্চারাইজ রাখে এবং ফাটা ঠোঁট সারিয়ে তোলে। দৈনন্দিন ব্যবহারে একদম পারফেক্ট।",
    image: "https://i.ibb.co.com/VW2w2FrX/Leonardo-Phoenix-10-A-closeup-product-photo-of-a-matte-lipstic-3.jpg"
  },
  {
    id: 6,
    name: "ব্লাশ অন",
    brand: "রিকল",
    category: "ব্লাশ",
    shade: "পিচ গ্লো",
    price: 350,
    discount: 8,
    stock: 45,
    description: "রিকল ব্লাশ অন ‘পিচ গ্লো’ আপনার গালকে দিবে একটি প্রাকৃতিক ও উজ্জ্বল রঙের আভা। এটি সহজেই ব্লেন্ড হয় এবং দীর্ঘস্থায়ী ফিনিশ দেয়।",
    image:  "https://i.ibb.co.com/VW2w2FrX/Leonardo-Phoenix-10-A-closeup-product-photo-of-a-matte-lipstic-3.jpg"
  },
  {
    id: 7,
    name: "আইশ্যাডো প্যালেট",
    brand: "হুদা বিউটি",
    category: "আইশ্যাডো",
    shade: "নুড কালেকশন",
    price: 850,
    discount: 12,
    stock: 25,
    description: "হুদা বিউটির এই আইশ্যাডো প্যালেট-এ রয়েছে ১২টি রঙ, ম্যাট ও শিমার দুটো ফিনিশেই। পার্টি ও ডেইলি লুকের জন্য আদর্শ।",
    image: "https://i.ibb.co.com/VW2w2FrX/Leonardo-Phoenix-10-A-closeup-product-photo-of-a-matte-lipstic-3.jpg"
  },
  {
    id: 8,
    name: "মেকআপ রিমুভার ওয়াইপস",
    brand: "গার্নিয়ার",
    category: "স্কিন কেয়ার",
    shade: "নরমাল স্কিন",
    price: 180,
    discount: 10,
    stock: 70,
    description: "গার্নিয়ারের এই ওয়াইপস মেকআপ সহজেই তুলে ফেলে এবং ত্বককে রাখে কোমল ও ময়েশ্চারাইজড। পারাবেন-মুক্ত এবং অ্যালার্জি টেস্টেড।",
    image: "https://i.ibb.co.com/VW2w2FrX/Leonardo-Phoenix-10-A-closeup-product-photo-of-a-matte-lipstic-3.jpg"
  },
  {
    id: 9,
    name: "মাস্কারা ভলিউমাইজিং",
    brand: "এলিগার্ল",
    category: "মাস্কারা",
    shade: "জেট ব্ল্যাক",
    price: 420,
    discount: 6,
    stock: 40,
    description: "এলিগার্ল মাস্কারা জেট ব্ল্যাক শেডে আপনার চোখকে দিবে নাটকীয় ভলিউম ও কার্ল। ওয়াটারপ্রুফ এবং সারা দিন টিকে থাকে।",
    image: "https://i.ibb.co.com/VW2w2FrX/Leonardo-Phoenix-10-A-closeup-product-photo-of-a-matte-lipstic-3.jpg"
  },
  {
    id: 10,
    name: "নেইল পলিশ সেট",
    brand: "নেইলইট",
    category: "নেইল কেয়ার",
    shade: "সামার কালেকশন",
    price: 299,
    discount: 7,
    stock: 55,
    description: "নেইলইট-এর এই নেইল পলিশ সেটে রয়েছে ৫টি চমৎকার গ্রীষ্মকালীন রঙ, দ্রুত শুকায় এবং দীর্ঘস্থায়ী গ্লসি ফিনিশ দেয়।",
    image:  "https://i.ibb.co.com/VW2w2FrX/Leonardo-Phoenix-10-A-closeup-product-photo-of-a-matte-lipstic-3.jpg"
  }
];


const designServices = [
  {
    name: "পোস্টার ডিজাইন",
    category: "গ্রাফিক ডিজাইন",
    description: "ইভেন্ট, প্রমোশন অথবা সোশ্যাল মিডিয়ার জন্য আকর্ষণীয় পোস্টার ডিজাইন।",
    price: 500,
    deliveryTime: "2 days",
    revision: 2,
    image: "https://i.ibb.co.com/gbmKDRBP/34199613-609.jpg"
  },
  {
    name: "ব্যানার ডিজাইন",
    category: "গ্রাফিক ডিজাইন",
    description: "ওয়েবসাইট, ফেসবুক কভার অথবা বিজ্ঞাপনের জন্য ব্যানার তৈরি।",
    price: 600,
    deliveryTime: "2 days",
    revision: 2,
    image: "https://i.ibb.co.com/dsvx09rv/122159578-433.jpg"
  },
  {
    name: "লোগো ডিজাইন",
    category: "ব্র্যান্ডিং",
    description: "বিজনেস বা পার্সোনাল ব্র্যান্ডিং এর জন্য ইউনিক লোগো তৈরি।",
    price: 1000,
    deliveryTime: "3 days",
    revision: 3,
    image: "https://i.ibb.co.com/ycskTMk0/34484430-shoesoct10.jpg"
  },
  {
    name: "ইউটিউব থাম্বনেইল ডিজাইন",
    category: "সোশ্যাল মিডিয়া",
    description: "ইউটিউব ভিডিওর জন্য হাই-কোয়ালিটি ও ক্লিক-বেইট থাম্বনেইল ডিজাইন।",
    price: 300,
    deliveryTime: "1 day",
    revision: 1,
    image: "https://i.ibb.co.com/G4qwy6BL/7009951-3514068.jpg"
  },
  {
    name: "সোশ্যাল মিডিয়া পোস্ট ডিজাইন",
    category: "সোশ্যাল মিডিয়া",
    description: "ইনস্টাগ্রাম, ফেসবুক ও অন্যান্য সোশ্যাল প্ল্যাটফর্মের জন্য পোস্ট ডিজাইন।",
    price: 400,
    deliveryTime: "1 day",
    revision: 2,
    image: "https://i.ibb.co.com/qYq1G6KG/7009949-3514341.jpg"
  },
  {
    name: "ভিজিটিং কার্ড ডিজাইন",
    category: "প্রিন্ট ডিজাইন",
    description: "প্রফেশনাল ও ইউনিক ভিজিটিং কার্ড ডিজাইন।",
    price: 350,
    deliveryTime: "2 days",
    revision: 2,
    image: "https://i.ibb.co.com/gbmKDRBP/34199613-609.jpg"
  },
  {
    name: "ফ্লায়ার ডিজাইন",
    category: "প্রিন্ট ডিজাইন",
    description: "প্রচার, অফার অথবা ইভেন্টের জন্য রঙিন ফ্লায়ার ডিজাইন।",
    price: 500,
    deliveryTime: "2 days",
    revision: 2,
    image: "https://i.ibb.co.com/dsvx09rv/122159578-433.jpg"
  },
  {
    name: "ই-বুক কাভার ডিজাইন",
    category: "বুক ডিজাইন",
    description: "ই-বুক অথবা প্রিন্ট বুকের জন্য আকর্ষণীয় কাভার ডিজাইন।",
    price: 800,
    deliveryTime: "3 days",
    revision: 2,
    image: "https://i.ibb.co.com/ycskTMk0/34484430-shoesoct10.jpg"
  },
  {
    name: "ইনফোগ্রাফিক ডিজাইন",
    category: "ডেটা ভিজ্যুয়াল",
    description: "তথ্য উপস্থাপনায় আকর্ষণীয় ও সহজবোধ্য ইনফোগ্রাফিক ডিজাইন।",
    price: 700,
    deliveryTime: "3 days",
    revision: 2,
    image: "https://i.ibb.co.com/G4qwy6BL/7009951-3514068.jpg"
  },
  {
    name: "মেনু ডিজাইন",
    category: "প্রিন্ট ডিজাইন",
    description: "রেস্টুরেন্ট বা ক্যাফের জন্য প্রফেশনাল মেনু ডিজাইন।",
    price: 600,
    deliveryTime: "2 days",
    revision: 2,
    image: "https://i.ibb.co.com/qYq1G6KG/7009949-3514341.jpg"
  }
]


export  {
  clothingData,
 
  hospitalData,
  medicineData,
  mobileAppData,
  websiteData,
  beautyProducts,
  designServices
};
