const doctorData = [
  {
    name: "ডা. লামিয়া হক",
    degree: "এমবিবিএস, এফসিপিএস",
    specialty: "নিউরোলজিস্ট",
    experience: "11+ years",
    bmdc_number: "A25765",
    rating: "4.5 (1655)",
    hospital: "সরকারি হাসপাতাল, ঢাকা",
    consultation_fee: "৳600 (incl. VAT)",
    follow_up_fee: "৳300 (within 14 days)",
    languages: "বাংলা, ইংরেজি",
    consultation_time: {
      instant: "শনিবার - বৃহস্পতিবার (৩টা - ৯টা)",
      appointment: "রবিবার (১০টা - ১২টা)",
    },
    patients_attended: "4314+",
    avg_consultation_time: "11 minutes",
    joined_date: "2020-08-16",
    doctor_code: "DT7403",
    profile_image:
      "https://i.ibb.co.com/S4wvgcNw/Leonardo-Phoenix-10-A-professional-profile-image-of-a-Banglade-2-1.jpg",
  },
  {
    name: "ডা. রুবাইয়া সুলতানা",
    degree: "এমবিবিএস, এমএস",
    specialty: "ইএনটি বিশেষজ্ঞ",
    experience: "10+ years",
    bmdc_number: "B79669",
    rating: "4.7 (1868)",
    hospital: "সরকারি হাসপাতাল, ঢাকা",
    consultation_fee: "৳500 (incl. VAT)",
    follow_up_fee: "৳200 (within 14 days)",
    languages: "বাংলা, ইংরেজি",
    consultation_time: {
      instant: "শনিবার - বৃহস্পতিবার (৩টা - ৯টা)",
      appointment: "রবিবার (১০টা - ১২টা)",
    },
    patients_attended: "6988+",
    avg_consultation_time: "19 minutes",
    joined_date: "2021-12-22",
    doctor_code: "DT8428",
    profile_image:
      "https://i.ibb.co.com/S4wvgcNw/Leonardo-Phoenix-10-A-professional-profile-image-of-a-Banglade-2-1.jpg",
  },
  {
    name: "ডা. ফারজানা কবির",
    degree: "এমবিবিএস, এমএস",
    specialty: "গাইনিকোলজিস্ট",
    experience: "14+ years",
    bmdc_number: "C23573",
    rating: "4.6 (1079)",
    hospital: "সরকারি হাসপাতাল, ঢাকা",
    consultation_fee: "৳500 (incl. VAT)",
    follow_up_fee: "৳300 (within 14 days)",
    languages: "বাংলা, ইংরেজি",
    consultation_time: {
      instant: "শনিবার - বৃহস্পতিবার (৩টা - ৯টা)",
      appointment: "রবিবার (১০টা - ১২টা)",
    },
    patients_attended: "7040+",
    avg_consultation_time: "18 minutes",
    joined_date: "2021-01-18",
    doctor_code: "DT5733",
    profile_image:
      "https://i.ibb.co.com/mCMytgX8/Leonardo-Phoenix-10-A-professional-profile-image-of-a-Banglade-3-1.jpg",
  },
  {
    name: "ডা. তানজিলা রহমান",
    degree: "এমবিবিএস, এফসিপিএস",
    specialty: "চাইল্ড স্পেশালিস্ট",
    experience: "14+ years",
    bmdc_number: "D44006",
    rating: "4.6 (1171)",
    hospital: "সরকারি হাসপাতাল, ঢাকা",
    consultation_fee: "৳400 (incl. VAT)",
    follow_up_fee: "৳300 (within 14 days)",
    languages: "বাংলা, ইংরেজি",
    consultation_time: {
      instant: "শনিবার - বৃহস্পতিবার (৩টা - ৯টা)",
      appointment: "রবিবার (১০টা - ১২টা)",
    },
    patients_attended: "7224+",
    avg_consultation_time: "12 minutes",
    joined_date: "2022-09-17",
    doctor_code: "DT8783",
    profile_image:
      "https://i.ibb.co.com/N28Wr2gK/Leonardo-Phoenix-10-A-professional-profile-image-of-a-Banglade-0.jpg",
  },
  {
    name: "ডা. শারমিন আক্তার",
    degree: "এমবিবিএস, এফসিপিএস",
    specialty: "ডার্মাটোলজিস্ট",
    experience: "15+ years",
    bmdc_number: "E79628",
    rating: "4.8 (1067)",
    hospital: "সরকারি হাসপাতাল, ঢাকা",
    consultation_fee: "৳600 (incl. VAT)",
    follow_up_fee: "৳300 (within 14 days)",
    languages: "বাংলা, ইংরেজি",
    consultation_time: {
      instant: "শনিবার - বৃহস্পতিবার (৩টা - ৯টা)",
      appointment: "রবিবার (১০টা - ১২টা)",
    },
    patients_attended: "7201+",
    avg_consultation_time: "20 minutes",
    joined_date: "2021-12-26",
    doctor_code: "DT5409",
    profile_image:
      "https://i.ibb.co.com/pBKphb73/Leonardo-Phoenix-10-A-professional-profile-image-of-a-Banglade-1-1.jpg",
  },
  {
    name: "ডা. সাবিহা আলম",
    degree: "এমবিবিএস, এমডি",
    specialty: "কার্ডিওলজিস্ট",
    experience: "7+ years",
    bmdc_number: "F38016",
    rating: "4.8 (1064)",
    hospital: "সরকারি হাসপাতাল, ঢাকা",
    consultation_fee: "৳700 (incl. VAT)",
    follow_up_fee: "৳350 (within 14 days)",
    languages: "বাংলা, ইংরেজি",
    consultation_time: {
      instant: "শনিবার - বৃহস্পতিবার (৩টা - ৯টা)",
      appointment: "রবিবার (১০টা - ১২টা)",
    },
    patients_attended: "6610+",
    avg_consultation_time: "14 minutes",
    joined_date: "2020-01-20",
    doctor_code: "DT6547",
    profile_image:
      "https://i.ibb.co.com/N28Wr2gK/Leonardo-Phoenix-10-A-professional-profile-image-of-a-Banglade-0.jpg",
  },
  {
    name: "ডা. মাহিরা খন্দকার",
    degree: "এমবিবিএস, এমফিল",
    specialty: "পেডিয়াট্রিশিয়ান",
    experience: "8+ years",
    bmdc_number: "G86313",
    rating: "4.5 (1300)",
    hospital: "সরকারি হাসপাতাল, ঢাকা",
    consultation_fee: "৳600 (incl. VAT)",
    follow_up_fee: "৳250 (within 14 days)",
    languages: "বাংলা, ইংরেজি",
    consultation_time: {
      instant: "শনিবার - বৃহস্পতিবার (৩টা - ৯টা)",
      appointment: "রবিবার (১০টা - ১২টা)",
    },
    patients_attended: "4728+",
    avg_consultation_time: "12 minutes",
    joined_date: "2020-04-03",
    doctor_code: "DT5825",
    profile_image:
      "https://i.ibb.co.com/N28Wr2gK/Leonardo-Phoenix-10-A-professional-profile-image-of-a-Banglade-0.jpg",
  },
  {
    name: "ডা. সুমাইয়া জামান",
    degree: "এমবিবিএস, এমএস",
    specialty: "এন্ডোক্রিনোলজিস্ট",
    experience: "6+ years",
    bmdc_number: "H13565",
    rating: "5.0 (1935)",
    hospital: "সরকারি হাসপাতাল, ঢাকা",
    consultation_fee: "৳600 (incl. VAT)",
    follow_up_fee: "৳200 (within 14 days)",
    languages: "বাংলা, ইংরেজি",
    consultation_time: {
      instant: "শনিবার - বৃহস্পতিবার (৩টা - ৯টা)",
      appointment: "রবিবার (১০টা - ১২টা)",
    },
    patients_attended: "6418+",
    avg_consultation_time: "14 minutes",
    joined_date: "2020-04-12",
    doctor_code: "DT9092",
    profile_image:
      "https://i.ibb.co.com/N28Wr2gK/Leonardo-Phoenix-10-A-professional-profile-image-of-a-Banglade-0.jpg",
  },
  {
    name: "ডা. ফারিয়া হাসান",
    degree: "এমবিবিএস, এমডি",
    specialty: "নেফ্রোলজিস্ট",
    experience: "14+ years",
    bmdc_number: "I79527",
    rating: "4.8 (1231)",
    hospital: "সরকারি হাসপাতাল, ঢাকা",
    consultation_fee: "৳600 (incl. VAT)",
    follow_up_fee: "৳300 (within 14 days)",
    languages: "বাংলা, ইংরেজি",
    consultation_time: {
      instant: "শনিবার - বৃহস্পতিবার (৩টা - ৯টা)",
      appointment: "রবিবার (১০টা - ১২টা)",
    },
    patients_attended: "4805+",
    avg_consultation_time: "16 minutes",
    joined_date: "2020-06-02",
    doctor_code: "DT4756",
    profile_image:
      "https://i.ibb.co.com/kVYcvKyx/Leonardo-Phoenix-10-A-professional-profile-image-of-a-Banglade-3.jpg",
  },
  {
    name: "ডা. নুসরাত জাহান",
    degree: "এমবিবিএস, এমফিল",
    specialty: "জেনারেল ফিজিশিয়ান",
    experience: "7+ years",
    bmdc_number: "J47543",
    rating: "4.7 (1258)",
    hospital: "সরকারি হাসপাতাল, ঢাকা",
    consultation_fee: "৳700 (incl. VAT)",
    follow_up_fee: "৳250 (within 14 days)",
    languages: "বাংলা, ইংরেজি",
    consultation_time: {
      instant: "শনিবার - বৃহস্পতিবার (৩টা - ৯টা)",
      appointment: "রবিবার (১০টা - ১২টা)",
    },
    patients_attended: "7944+",
    avg_consultation_time: "16 minutes",
    joined_date: "2021-07-18",
    doctor_code: "DT4139",
    profile_image:
      "https://i.ibb.co.com/YFHdsmbF/Leonardo-Phoenix-10-A-professional-profile-image-of-a-Banglade-2.jpg",
  },
];

const hospitalData = [
  {
    appointmentId: "APPT-20231027-001",
    hospital: {
      hospitalId: "HOSP-001",
      hospitalName: "সিটি জেনারেল হাসপাতাল",
      address: "১০ হাসপাতাল রোড, যেকোনো শহর",
      contactNumber: "৫৫৫-১০০-২০০০",
      imageUrl:
        "https://i.ibb.co.com/ym6QDhww/Gemini-Generated-Image-a31u5na31u5na31u.jpg",
      website: "www.citygeneralhospital.com", // Added website address
    },
    doctor: {
      doctorId: "DR-67890",
      firstName: "রবার্ট",
      lastName: "স্মিথ",
      specialization: "কার্ডিওলজি",
    },
    appointmentDate: "২০২৩-১১-১৫",
    appointmentTime: "১০:০০",
    location: "কার্ডিওলজি ক্লিনিক, ২য় তলা",
    reasonForVisit: "ফলো-আপ চেকআপ",
    notes: "সাম্প্রতিক রক্ত পরীক্ষার ফলাফল আনুন।",
    fees: {
      amount: 1500,
      currency: "BDT",
    },
    paymentStatus: "Paid",
  },
  {
    appointmentId: "APPT-20231027-002",
    hospital: {
      hospitalId: "HOSP-002",
      hospitalName: "আঞ্চলিক মেডিকেল সেন্টার",
      address: "২৫ মেডিকেল এভিনিউ, যেকোনো শহর",
      contactNumber: "৫৫৫-২০০-৩০০০",
      imageUrl:
        "https://i.ibb.co.com/9HxGn3C1/Gemini-Generated-Image-tdpa5etdpa5etdpa.jpg",
      website: "www.regionalmedicalcenter.com", // Added website address
    },
    doctor: {
      doctorId: "DR-13579",
      firstName: "এমিলি",
      lastName: "ডেভিস",
      specialization: "ডার্মাটোলজি",
    },
    appointmentDate: "২০২৩-১১-১৬",
    appointmentTime: "১৪:৩০",
    location: "ডার্মাটোলজি ক্লিনিক, ৩য় তলা",
    reasonForVisit: "ত্বকের ফুসকুড়ি মূল্যায়ন",
    notes: "অ্যাপয়েন্টমেন্টের আগে লোশন বা ক্রিম লাগানো এড়িয়ে চলুন।",
    fees: {
      amount: 2000,
      currency: "BDT",
    },
    paymentStatus: "Pending",
  },
  {
    appointmentId: "APPT-20231027-003",
    hospital: {
      hospitalId: "HOSP-003",
      hospitalName: "সেন্ট লুকস হাসপাতাল",
      address: "৪০ চার্চ স্ট্রিট, যেকোনো শহর",
      contactNumber: "৫৫৫-৩০০-৪০০০",
      imageUrl:
        "https://i.ibb.co.com/MD6vQsts/Gemini-Generated-Image-4gg28v4gg28v4gg2.jpg",
      website: "www.stlukeshospital.com", // Added website address
    },
    doctor: {
      doctorId: "DR-24680",
      firstName: "মাইকেল",
      lastName: "উইলসন",
      specialization: "পেডিয়াট্রিক্স",
    },
    appointmentDate: "২০২৩-১১-১৭",
    appointmentTime: "০৯:১৫",
    location: "পেডিয়াট্রিক্স ক্লিনিক, ১ম তলা",
    reasonForVisit: "বার্ষিক চেকআপ",
    notes: "টিকা দেওয়ার রেকর্ড আনুন।",
    fees: {
      amount: 1200,
      currency: "BDT",
    },
    paymentStatus: "Paid",
  },
  {
    appointmentId: "APPT-20231027-004",
    hospital: {
      hospitalId: "HOSP-004",
      hospitalName: "কমিউনিটি হেলথ ক্লিনিক",
      address: "১৫ মেইন স্ট্রিট, যেকোনো শহর",
      contactNumber: "৫৫৫-৪০০-৫০০০",
      imageUrl:
        "https://i.ibb.co.com/B5xk6KBB/Gemini-Generated-Image-e7cpye7cpye7cpye.jpg",
      website: "www.communityhealthclinic.org", // Added website address
    },
    doctor: {
      doctorId: "DR-98765",
      firstName: "জেসিকা",
      lastName: "মুর",
      specialization: "অর্থোপেডিক্স",
    },
    appointmentDate: "২০২৩-১১-১৮",
    appointmentTime: "১১:০০",
    location: "অর্থোপেডিক্স ক্লিনিক, ৪র্থ তলা",
    reasonForVisit: "হাঁটু ব্যথার মূল্যায়ন",
    notes: "আরামদায়ক পোশাক পরুন।",
    fees: {
      amount: 2500,
      currency: "BDT",
    },
    paymentStatus: "Partially Paid",
  },
  {
    appointmentId: "APPT-20231027-005",
    hospital: {
      hospitalId: "HOSP-005",
      hospitalName: "স্পেশালিটি সার্জিক্যাল সেন্টার",
      address: "৩০ সার্জিক্যাল ড্রাইভ, যেকোনো শহর",
      contactNumber: "৫৫৫-৫০০-৬০০০",
      imageUrl:
        "https://i.ibb.co.com/4wTp4Jvr/Gemini-Generated-Image-aa1y5aaa1y5aaa1y.jpg",
      website: "www.specialtysurgicalcenter.com", // Added website address
    },
    doctor: {
      doctorId: "DR-36912",
      firstName: "ডেভিড",
      lastName: "টেইলর",
      specialization: "নিউরোলোজি",
    },
    appointmentDate: "২০২৩-১১-১৯",
    appointmentTime: "১৫:৪৫",
    location: "নিউরোলোজি ক্লিনিক, ৫ম তলা",
    reasonForVisit: "মাইগ্রেন মূল্যায়ন",
    notes: "সাম্প্রতিক মাথাব্যথার একটি লগ রাখুন।",
    fees: {
      amount: 3000,
      currency: "BDT",
    },
    paymentStatus: "Not Paid",
  },
  {
    appointmentId: "APPT-20231028-006",
    hospital: {
      hospitalId: "HOSP-001",
      hospitalName: "সিটি জেনারেল হাসপাতাল",
      address: "১০ হাসপাতাল রোড, যেকোনো শহর",
      contactNumber: "৫৫৫-১০০-২০০০",
      imageUrl:
        "https://i.ibb.co.com/ym6QDhww/Gemini-Generated-Image-a31u5na31u5na31u.jpg",
      website: "www.citygeneralhospital.com", // Added website address
    },
    doctor: {
      doctorId: "DR-11223",
      firstName: "সোফিয়া",
      lastName: "রহমান",
      specialization: "গাইনোকোলজি",
    },
    appointmentDate: "২০২৩-১১-২০",
    appointmentTime: "১২:০০",
    location: "গাইনোকোলজি ক্লিনিক, ৬ষ্ঠ তলা",
    reasonForVisit: "প্রসবপূর্ব চেকআপ",
    notes: "আল্ট্রাসাউন্ড রিপোর্ট আনুন।",
    fees: {
      amount: 2800,
      currency: "BDT",
    },
    paymentStatus: "Paid",
  },
  {
    appointmentId: "APPT-20231028-007",
    hospital: {
      hospitalId: "HOSP-002",
      hospitalName: "আঞ্চলিক মেডিকেল সেন্টার",
      address: "২৫ মেডিকেল এভিনিউ, যেকোনো শহর",
      contactNumber: "৫৫৫-২০০-৩০০০",
      imageUrl:
        "https://i.ibb.co.com/9HxGn3C1/Gemini-Generated-Image-tdpa5etdpa5etdpa.jpg",
      website: "www.regionalmedicalcenter.com", // Added website address
    },
    doctor: {
      doctorId: "DR-44556",
      firstName: "আরিফ",
      lastName: "হোসেন",
      specialization: "ইউরোলজি",
    },
    appointmentDate: "২০২৩-১১-২১",
    appointmentTime: "১৪:৪৫",
    location: "ইউরোলজি ক্লিনিক, ৭ম তলা",
    reasonForVisit: "কিডনি স্টোন চেকআপ",
    notes: "রক্ত ও ইউরিন টেস্ট রিপোর্ট আনুন।",
    fees: {
      amount: 3200,
      currency: "BDT",
    },
    paymentStatus: "Pending",
  },
  {
    appointmentId: "APPT-20231028-008",
    hospital: {
      hospitalId: "HOSP-003",
      hospitalName: "সেন্ট লুকস হাসপাতাল",
      address: "৪০ চার্চ স্ট্রিট, যেকোনো শহর",
      contactNumber: "৫৫৫-৩০০-৪০০০",
      imageUrl:
        "https://i.ibb.co.com/MD6vQsts/Gemini-Generated-Image-4gg28v4gg28v4gg2.jpg",
      website: "www.stlukeshospital.com", // Added website address
    },
    doctor: {
      doctorId: "DR-77889",
      firstName: "ফারজানা",
      lastName: "আক্তার",
      specialization: "অপথালমোলজি",
    },
    appointmentDate: "২০২৩-১১-২২",
    appointmentTime: "১০:৩০",
    location: "অপথালমোলজি ক্লিনিক, ৮ম তলা",
    reasonForVisit: "চোখের সাধারণ চেকআপ",
    notes: "চোখের চশমার প্রেসক্রিপশন আনুন।",
    fees: {
      amount: 1800,
      currency: "BDT",
    },
    paymentStatus: "Paid",
  },
  {
    appointmentId: "APPT-20231028-009",
    hospital: {
      hospitalId: "HOSP-004",
      hospitalName: "কমিউনিটি হেলথ ক্লিনিক",
      address: "১৫ মেইন স্ট্রিট, যেকোনো শহর",
      contactNumber: "৫৫৫-৪০০-৫০০০",
      imageUrl:
        "https://i.ibb.co.com/B5xk6KBB/Gemini-Generated-Image-e7cpye7cpye7cpye.jpg",
      website: "www.communityhealthclinic.org", // Added website address
    },
    doctor: {
      doctorId: "DR-99001",
      firstName: "ইমরান",
      lastName: "কবির",
      specialization: "ইএনটি",
    },
    appointmentDate: "২০২৩-১১-২৩",
    appointmentTime: "১১:৪৫",
    location: "ইএনটি ক্লিনিক, ৯ম তলা",
    reasonForVisit: "নাক ও গলার সমস্যা",
    notes: "পূর্বের কোনো টেস্ট রিপোর্ট থাকলে আনুন।",
    fees: {
      amount: 2200,
      currency: "BDT",
    },
    paymentStatus: "Partially Paid",
  },
  {
    appointmentId: "APPT-20231028-010",
    hospital: {
      hospitalId: "HOSP-005",
      hospitalName: "স্পেশালিটি সার্জিক্যাল সেন্টার",
      address: "৩০ সার্জিক্যাল ড্রাইভ, যেকোনো শহর",
      contactNumber: "৫৫৫-৫০০-৬০০০",
      imageUrl:
        "https://i.ibb.co.com/4wTp4Jvr/Gemini-Generated-Image-aa1y5aaa1y5aaa1y.jpg",
      website: "www.specialtysurgicalcenter.com", // Added website address
    },
    doctor: {
      doctorId: "DR-22334",
      firstName: "সাদিয়া",
      lastName: "আহমেদ",
      specialization: "প্লাস্টিক সার্জারি",
    },
    appointmentDate: "২০২৩-১১-২৪",
    appointmentTime: "১৫:৩০",
    location: "প্লাস্টিক সার্জারি ক্লিনিক, ১০ম তলা",
    reasonForVisit: "পোড়া দাগের চিকিৎসা",
    notes: "পূর্বের চিকিৎসার ছবি আনুন।",
    fees: {
      amount: 3500,
      currency: "BDT",
    },
    paymentStatus: "Not Paid",
  },
];

const medicineData = [
  {
    id: "med001",
    name: "Paracetamol 500mg",
    brand: "ACME Pharma",
    category: "Pain Reliever",
    price: "30",
    discount: "5",
    stock: "100",
    expiry_date: "2026-01-15",
    description: "Relieves pain and reduces fever.",
    prescription_required: "false",
    image: "https://i.ibb.co.com/jPMr51ms/Leonardo-Phoenix-10-Create-a-highquality-product-image-of-a-me-0-2.jpg"
  },
  {
    id: "med002",
    name: "Azithromycin 250mg",
    brand: "Square Pharmaceuticals",
    category: "Antibiotic",
    price: "120",
    discount: "10",
    stock: "50",
    expiry_date: "2025-12-01",
    description: "Treats bacterial infections.",
    prescription_required: "true",
    image: "https://i.ibb.co.com/WWQ1SN64/Leonardo-Phoenix-10-Create-a-highquality-product-image-of-a-me-0-1.jpg"
  },
  {
    id: "med003",
    name: "Cetirizine 10mg",
    brand: "Renata Limited",
    category: "Antihistamine",
    price: "20",
    discount: "0",
    stock: "200",
    expiry_date: "2026-06-30",
    description: "Allergy relief for runny nose, sneezing, etc.",
    prescription_required: "false",
    image: "https://i.ibb.co.com/7xcFc89w/Leonardo-Phoenix-10-Create-a-highquality-product-image-of-a-me-1-1.jpg"
  },
  {
    id: "med004",
    name: "Omeprazole 20mg",
    brand: "Beximco Pharma",
    category: "Antacid",
    price: "50",
    discount: "8",
    stock: "80",
    expiry_date: "2025-10-20",
    description: "Treats acid reflux and ulcers.",
    prescription_required: "false",
    image: "https://i.ibb.co.com/0jrhbqbZ/Leonardo-Phoenix-10-Create-a-highquality-product-image-of-a-me-2-1.jpg"
  },
  {
    id: "med005",
    name: "Metformin 500mg",
    brand: "Eskayef Pharmaceuticals",
    category: "Diabetes",
    price: "60",
    discount: "5",
    stock: "70",
    expiry_date: "2026-02-28",
    description: "Controls blood sugar levels.",
    prescription_required: "true",
    image: "https://i.ibb.co.com/0R96qgTj/Leonardo-Phoenix-10-Create-a-highquality-product-image-of-a-me-3-1.jpg"
  },
  {
    id: "med006",
    name: "Amlodipine 5mg",
    brand: "Incepta Pharmaceuticals",
    category: "Blood Pressure",
    price: "40",
    discount: "5",
    stock: "90",
    expiry_date: "2025-09-01",
    description: "Treats high blood pressure and chest pain.",
    prescription_required: "true",
    image: "https://i.ibb.co.com/Zzc89KDw/Leonardo-Phoenix-10-Create-a-highquality-product-image-of-a-me-3.jpg"
  },
  {
    id: "med007",
    name: "Losartan 50mg",
    brand: "ACI Limited",
    category: "Blood Pressure",
    price: "45",
    discount: "3",
    stock: "60",
    expiry_date: "2026-01-01",
    description: "Used for treating high blood pressure.",
    prescription_required: "true",
    image: "https://i.ibb.co.com/NMFz4KJ/Leonardo-Phoenix-10-Create-a-highquality-product-image-of-a-me-2.jpg"
  },
  {
    id: "med008",
    name: "Montelukast 10mg",
    brand: "Healthcare Pharmaceuticals",
    category: "Asthma",
    price: "55",
    discount: "7",
    stock: "100",
    expiry_date: "2026-03-10",
    description: "Prevents asthma symptoms and allergies.",
    prescription_required: "false",
    image: "https://i.ibb.co.com/zT9Ckhf6/Leonardo-Phoenix-10-Create-a-highquality-product-image-of-a-me-1.jpg"
  },
  {
    id: "med009",
    name: "Loratadine 10mg",
    brand: "Opsonin Pharma",
    category: "Antihistamine",
    price: "18",
    discount: "0",
    stock: "150",
    expiry_date: "2026-07-01",
    description: "Relieves hay fever and allergy symptoms.",
    prescription_required: "false",
    image: "https://i.ibb.co.com/PG3K5hbG/Leonardo-Phoenix-10-Create-a-highquality-product-image-of-a-me-0.jpg"
  },
  {
    id: "med010",
    name: "Rabeprazole 20mg",
    brand: "Beximco Pharma",
    category: "Antacid",
    price: "52",
    discount: "5",
    stock: "75",
    expiry_date: "2025-11-25",
    description: "Treats gastroesophageal reflux disease (GERD).",
    prescription_required: "false",
    image: "https://i.ibb.co.com/MxknkzC6/Leonardo-Phoenix-10-Create-a-highquality-product-image-of-a-me-3-4.jpg"
  },
  {
    id: "med021",
    name: "Doxycycline 100mg",
    brand: "Square Pharmaceuticals",
    category: "Antibiotic",
    price: "110",
    discount: "5",
    stock: "50",
    expiry_date: "2026-03-15",
    description: "Used to treat bacterial infections.",
    prescription_required: "true",
    image: "https://i.ibb.co.com/sample1.jpg"
  },
  {
    id: "med022",
    name: "Atorvastatin 20mg",
    brand: "Incepta Pharmaceuticals",
    category: "Cholesterol",
    price: "80",
    discount: "6",
    stock: "60",
    expiry_date: "2025-12-01",
    description: "Reduces cholesterol levels.",
    prescription_required: "true",
    image: "https://i.ibb.co.com/sample2.jpg"
  },
  {
    id: "med023",
    name: "Calcium Carbonate",
    brand: "Renata Limited",
    category: "Supplements",
    price: "35",
    discount: "3",
    stock: "100",
    expiry_date: "2026-08-10",
    description: "Helps build and maintain strong bones.",
    prescription_required: "false",
    image: "https://i.ibb.co.com/sample3.jpg"
  },
  {
    id: "med024",
    name: "Levocetirizine 5mg",
    brand: "ACME Pharma",
    category: "Antihistamine",
    price: "22",
    discount: "2",
    stock: "200",
    expiry_date: "2026-01-25",
    description: "Relieves allergy symptoms.",
    prescription_required: "false",
    image: "https://i.ibb.co.com/sample4.jpg"
  },
  {
    id: "med025",
    name: "Amoxicillin 500mg",
    brand: "Beximco Pharma",
    category: "Antibiotic",
    price: "65",
    discount: "4",
    stock: "70",
    expiry_date: "2025-10-30",
    description: "Treats bacterial infections.",
    prescription_required: "true",
    image: "https://i.ibb.co.com/sample5.jpg"
  },
  {
    id: "med026",
    name: "Folic Acid 5mg",
    brand: "ACI Limited",
    category: "Supplements",
    price: "18",
    discount: "0",
    stock: "90",
    expiry_date: "2026-07-20",
    description: "Supports red blood cell formation.",
    prescription_required: "false",
    image: "https://i.ibb.co.com/sample6.jpg"
  },
  {
    id: "med027",
    name: "Thyroxine 50mcg",
    brand: "GSK",
    category: "Thyroid",
    price: "40",
    discount: "5",
    stock: "80",
    expiry_date: "2026-04-01",
    description: "Treats thyroid hormone deficiency.",
    prescription_required: "true",
    image: "https://i.ibb.co.com/sample7.jpg"
  },
  {
    id: "med028",
    name: "Pantoprazole 40mg",
    brand: "Healthcare Pharmaceuticals",
    category: "Antacid",
    price: "48",
    discount: "6",
    stock: "110",
    expiry_date: "2026-05-01",
    description: "Reduces stomach acid.",
    prescription_required: "false",
    image: "https://i.ibb.co.com/sample8.jpg"
  },
  {
    id: "med029",
    name: "Domperidone 10mg",
    brand: "Opsonin Pharma",
    category: "Digestive",
    price: "30",
    discount: "3",
    stock: "120",
    expiry_date: "2026-01-15",
    description: "Treats nausea and vomiting.",
    prescription_required: "false",
    image: "https://i.ibb.co.com/sample9.jpg"
  },
  {
    id: "med030",
    name: "Bisoprolol 5mg",
    brand: "Incepta Pharmaceuticals",
    category: "Blood Pressure",
    price: "38",
    discount: "4",
    stock: "90",
    expiry_date: "2026-06-20",
    description: "Used for treating high blood pressure.",
    prescription_required: "true",
    image: "https://i.ibb.co.com/sample10.jpg"
  },
  {
    id: "med031",
    name: "Magnesium Sulphate",
    brand: "Popular Pharma",
    category: "Supplements",
    price: "25",
    discount: "2",
    stock: "140",
    expiry_date: "2026-09-10",
    description: "Used for magnesium deficiency.",
    prescription_required: "false",
    image: "https://i.ibb.co.com/sample11.jpg"
  },
  {
    id: "med032",
    name: "Fluconazole 150mg",
    brand: "Square Pharmaceuticals",
    category: "Antifungal",
    price: "75",
    discount: "5",
    stock: "50",
    expiry_date: "2026-02-01",
    description: "Treats fungal infections.",
    prescription_required: "true",
    image: "https://i.ibb.co.com/sample12.jpg"
  },
  {
    id: "med033",
    name: "Hydroxychloroquine 200mg",
    brand: "ACI Limited",
    category: "Antimalarial",
    price: "95",
    discount: "8",
    stock: "30",
    expiry_date: "2025-08-25",
    description: "Used for malaria and autoimmune diseases.",
    prescription_required: "true",
    image: "https://i.ibb.co.com/sample13.jpg"
  },
  {
    id: "med034",
    name: "Cetirizine Syrup",
    brand: "Beximco Pharma",
    category: "Antihistamine",
    price: "45",
    discount: "3",
    stock: "100",
    expiry_date: "2026-01-01",
    description: "Relieves allergies in children.",
    prescription_required: "false",
    image: "https://i.ibb.co.com/sample14.jpg"
  },
  {
    id: "med035",
    name: "ORS Sachet",
    brand: "Renata Limited",
    category: "Rehydration",
    price: "12",
    discount: "0",
    stock: "300",
    expiry_date: "2026-12-31",
    description: "Prevents dehydration from diarrhea.",
    prescription_required: "false",
    image: "https://i.ibb.co.com/sample15.jpg"
  },
  {
    id: "med036",
    name: "Aspirin 75mg",
    brand: "ACME Pharma",
    category: "Cardiac",
    price: "28",
    discount: "3",
    stock: "130",
    expiry_date: "2026-03-01",
    description: "Used to prevent blood clots.",
    prescription_required: "true",
    image: "https://i.ibb.co.com/sample16.jpg"
  },
  {
    id: "med037",
    name: "Metronidazole 400mg",
    brand: "Square Pharmaceuticals",
    category: "Antibiotic",
    price: "33",
    discount: "2",
    stock: "100",
    expiry_date: "2026-02-15",
    description: "Treats parasitic and bacterial infections.",
    prescription_required: "true",
    image: "https://i.ibb.co.com/sample17.jpg"
  },
  {
    id: "med038",
    name: "Clotrimazole Cream",
    brand: "Incepta Pharmaceuticals",
    category: "Antifungal",
    price: "60",
    discount: "5",
    stock: "75",
    expiry_date: "2026-05-15",
    description: "Topical antifungal for skin infections.",
    prescription_required: "false",
    image: "https://i.ibb.co.com/sample18.jpg"
  },
  {
    id: "med039",
    name: "Saline IV",
    brand: "Popular Pharma",
    category: "Rehydration",
    price: "95",
    discount: "10",
    stock: "40",
    expiry_date: "2026-06-10",
    description: "Used for fluid replenishment.",
    prescription_required: "true",
    image: "https://i.ibb.co.com/sample19.jpg"
  },
  {
    id: "med040",
    name: "Simvastatin 10mg",
    brand: "Beximco Pharma",
    category: "Cholesterol",
    price: "70",
    discount: "6",
    stock: "60",
    expiry_date: "2026-07-20",
    description: "Lowers bad cholesterol and triglycerides.",
    prescription_required: "true",
    image: "https://i.ibb.co.com/sample20.jpg"
  }
];



export {hospitalData , doctorData , medicineData}