const doctorData = [
  {
    name: "ডা. লামিয়া হক",
    degree: "এমবিবিএস, এফসিপিএস",
    specialty: "নিউরোলজিস্ট",
    experience: "11+ years",
    bmdc_number: "A25765",
    rating: "4.5 (1655)",
    hospital: "সরকারি হাসপাতাল, ঢাকা",
    consultation_fee: "৳600 (incl. VAT)",
    follow_up_fee: "৳300 (within 14 days)",
    languages: "বাংলা, ইংরেজি",
    consultation_time: {
      instant: "শনিবার - বৃহস্পতিবার (৩টা - ৯টা)",
      appointment: "রবিবার (১০টা - ১২টা)",
    },
    patients_attended: "4314+",
    avg_consultation_time: "11 minutes",
    joined_date: "2020-08-16",
    doctor_code: "DT7403",
    profile_image:
      "https://i.ibb.co.com/S4wvgcNw/Leonardo-Phoenix-10-A-professional-profile-image-of-a-Banglade-2-1.jpg",
  },
  {
    name: "ডা. রুবাইয়া সুলতানা",
    degree: "এমবিবিএস, এমএস",
    specialty: "ইএনটি বিশেষজ্ঞ",
    experience: "10+ years",
    bmdc_number: "B79669",
    rating: "4.7 (1868)",
    hospital: "সরকারি হাসপাতাল, ঢাকা",
    consultation_fee: "৳500 (incl. VAT)",
    follow_up_fee: "৳200 (within 14 days)",
    languages: "বাংলা, ইংরেজি",
    consultation_time: {
      instant: "শনিবার - বৃহস্পতিবার (৩টা - ৯টা)",
      appointment: "রবিবার (১০টা - ১২টা)",
    },
    patients_attended: "6988+",
    avg_consultation_time: "19 minutes",
    joined_date: "2021-12-22",
    doctor_code: "DT8428",
    profile_image:
      "https://i.ibb.co.com/S4wvgcNw/Leonardo-Phoenix-10-A-professional-profile-image-of-a-Banglade-2-1.jpg",
  },
  {
    name: "ডা. ফারজানা কবির",
    degree: "এমবিবিএস, এমএস",
    specialty: "গাইনিকোলজিস্ট",
    experience: "14+ years",
    bmdc_number: "C23573",
    rating: "4.6 (1079)",
    hospital: "সরকারি হাসপাতাল, ঢাকা",
    consultation_fee: "৳500 (incl. VAT)",
    follow_up_fee: "৳300 (within 14 days)",
    languages: "বাংলা, ইংরেজি",
    consultation_time: {
      instant: "শনিবার - বৃহস্পতিবার (৩টা - ৯টা)",
      appointment: "রবিবার (১০টা - ১২টা)",
    },
    patients_attended: "7040+",
    avg_consultation_time: "18 minutes",
    joined_date: "2021-01-18",
    doctor_code: "DT5733",
    profile_image:
      "https://i.ibb.co.com/mCMytgX8/Leonardo-Phoenix-10-A-professional-profile-image-of-a-Banglade-3-1.jpg",
  },
  {
    name: "ডা. তানজিলা রহমান",
    degree: "এমবিবিএস, এফসিপিএস",
    specialty: "চাইল্ড স্পেশালিস্ট",
    experience: "14+ years",
    bmdc_number: "D44006",
    rating: "4.6 (1171)",
    hospital: "সরকারি হাসপাতাল, ঢাকা",
    consultation_fee: "৳400 (incl. VAT)",
    follow_up_fee: "৳300 (within 14 days)",
    languages: "বাংলা, ইংরেজি",
    consultation_time: {
      instant: "শনিবার - বৃহস্পতিবার (৩টা - ৯টা)",
      appointment: "রবিবার (১০টা - ১২টা)",
    },
    patients_attended: "7224+",
    avg_consultation_time: "12 minutes",
    joined_date: "2022-09-17",
    doctor_code: "DT8783",
    profile_image:
      "https://i.ibb.co.com/N28Wr2gK/Leonardo-Phoenix-10-A-professional-profile-image-of-a-Banglade-0.jpg",
  },
  {
    name: "ডা. শারমিন আক্তার",
    degree: "এমবিবিএস, এফসিপিএস",
    specialty: "ডার্মাটোলজিস্ট",
    experience: "15+ years",
    bmdc_number: "E79628",
    rating: "4.8 (1067)",
    hospital: "সরকারি হাসপাতাল, ঢাকা",
    consultation_fee: "৳600 (incl. VAT)",
    follow_up_fee: "৳300 (within 14 days)",
    languages: "বাংলা, ইংরেজি",
    consultation_time: {
      instant: "শনিবার - বৃহস্পতিবার (৩টা - ৯টা)",
      appointment: "রবিবার (১০টা - ১২টা)",
    },
    patients_attended: "7201+",
    avg_consultation_time: "20 minutes",
    joined_date: "2021-12-26",
    doctor_code: "DT5409",
    profile_image:
      "https://i.ibb.co.com/pBKphb73/Leonardo-Phoenix-10-A-professional-profile-image-of-a-Banglade-1-1.jpg",
  },
  {
    name: "ডা. সাবিহা আলম",
    degree: "এমবিবিএস, এমডি",
    specialty: "কার্ডিওলজিস্ট",
    experience: "7+ years",
    bmdc_number: "F38016",
    rating: "4.8 (1064)",
    hospital: "সরকারি হাসপাতাল, ঢাকা",
    consultation_fee: "৳700 (incl. VAT)",
    follow_up_fee: "৳350 (within 14 days)",
    languages: "বাংলা, ইংরেজি",
    consultation_time: {
      instant: "শনিবার - বৃহস্পতিবার (৩টা - ৯টা)",
      appointment: "রবিবার (১০টা - ১২টা)",
    },
    patients_attended: "6610+",
    avg_consultation_time: "14 minutes",
    joined_date: "2020-01-20",
    doctor_code: "DT6547",
    profile_image:
      "https://i.ibb.co.com/N28Wr2gK/Leonardo-Phoenix-10-A-professional-profile-image-of-a-Banglade-0.jpg",
  },
  {
    name: "ডা. মাহিরা খন্দকার",
    degree: "এমবিবিএস, এমফিল",
    specialty: "পেডিয়াট্রিশিয়ান",
    experience: "8+ years",
    bmdc_number: "G86313",
    rating: "4.5 (1300)",
    hospital: "সরকারি হাসপাতাল, ঢাকা",
    consultation_fee: "৳600 (incl. VAT)",
    follow_up_fee: "৳250 (within 14 days)",
    languages: "বাংলা, ইংরেজি",
    consultation_time: {
      instant: "শনিবার - বৃহস্পতিবার (৩টা - ৯টা)",
      appointment: "রবিবার (১০টা - ১২টা)",
    },
    patients_attended: "4728+",
    avg_consultation_time: "12 minutes",
    joined_date: "2020-04-03",
    doctor_code: "DT5825",
    profile_image:
      "https://i.ibb.co.com/N28Wr2gK/Leonardo-Phoenix-10-A-professional-profile-image-of-a-Banglade-0.jpg",
  },
  {
    name: "ডা. সুমাইয়া জামান",
    degree: "এমবিবিএস, এমএস",
    specialty: "এন্ডোক্রিনোলজিস্ট",
    experience: "6+ years",
    bmdc_number: "H13565",
    rating: "5.0 (1935)",
    hospital: "সরকারি হাসপাতাল, ঢাকা",
    consultation_fee: "৳600 (incl. VAT)",
    follow_up_fee: "৳200 (within 14 days)",
    languages: "বাংলা, ইংরেজি",
    consultation_time: {
      instant: "শনিবার - বৃহস্পতিবার (৩টা - ৯টা)",
      appointment: "রবিবার (১০টা - ১২টা)",
    },
    patients_attended: "6418+",
    avg_consultation_time: "14 minutes",
    joined_date: "2020-04-12",
    doctor_code: "DT9092",
    profile_image:
      "https://i.ibb.co.com/N28Wr2gK/Leonardo-Phoenix-10-A-professional-profile-image-of-a-Banglade-0.jpg",
  },
  {
    name: "ডা. ফারিয়া হাসান",
    degree: "এমবিবিএস, এমডি",
    specialty: "নেফ্রোলজিস্ট",
    experience: "14+ years",
    bmdc_number: "I79527",
    rating: "4.8 (1231)",
    hospital: "সরকারি হাসপাতাল, ঢাকা",
    consultation_fee: "৳600 (incl. VAT)",
    follow_up_fee: "৳300 (within 14 days)",
    languages: "বাংলা, ইংরেজি",
    consultation_time: {
      instant: "শনিবার - বৃহস্পতিবার (৩টা - ৯টা)",
      appointment: "রবিবার (১০টা - ১২টা)",
    },
    patients_attended: "4805+",
    avg_consultation_time: "16 minutes",
    joined_date: "2020-06-02",
    doctor_code: "DT4756",
    profile_image:
      "https://i.ibb.co.com/kVYcvKyx/Leonardo-Phoenix-10-A-professional-profile-image-of-a-Banglade-3.jpg",
  },
  {
    name: "ডা. নুসরাত জাহান",
    degree: "এমবিবিএস, এমফিল",
    specialty: "জেনারেল ফিজিশিয়ান",
    experience: "7+ years",
    bmdc_number: "J47543",
    rating: "4.7 (1258)",
    hospital: "সরকারি হাসপাতাল, ঢাকা",
    consultation_fee: "৳700 (incl. VAT)",
    follow_up_fee: "৳250 (within 14 days)",
    languages: "বাংলা, ইংরেজি",
    consultation_time: {
      instant: "শনিবার - বৃহস্পতিবার (৩টা - ৯টা)",
      appointment: "রবিবার (১০টা - ১২টা)",
    },
    patients_attended: "7944+",
    avg_consultation_time: "16 minutes",
    joined_date: "2021-07-18",
    doctor_code: "DT4139",
    profile_image:
      "https://i.ibb.co.com/YFHdsmbF/Leonardo-Phoenix-10-A-professional-profile-image-of-a-Banglade-2.jpg",
  },
];


const hospitalData = [
  {
    appointmentId: "APPT-20231027-001",
    hospital: {
      hospitalId: "HOSP-001",
      hospitalName: "সিটি জেনারেল হাসপাতাল",
      address: "১০ হাসপাতাল রোড, যেকোনো শহর",
      contactNumber: "৫৫৫-১০০-২০০০",
      imageUrl:
        "https://i.ibb.co.com/ym6QDhww/Gemini-Generated-Image-a31u5na31u5na31u.jpg",
      website: "www.citygeneralhospital.com", // Added website address
    },
    doctor: {
      doctorId: "DR-67890",
      firstName: "রবার্ট",
      lastName: "স্মিথ",
      specialization: "কার্ডিওলজি",
    },
    appointmentDate: "২০২৩-১১-১৫",
    appointmentTime: "১০:০০",
    location: "কার্ডিওলজি ক্লিনিক, ২য় তলা",
    reasonForVisit: "ফলো-আপ চেকআপ",
    notes: "সাম্প্রতিক রক্ত পরীক্ষার ফলাফল আনুন।",
    fees: {
      amount: 1500,
      currency: "BDT",
    },
    paymentStatus: "Paid",
  },
  {
    appointmentId: "APPT-20231027-002",
    hospital: {
      hospitalId: "HOSP-002",
      hospitalName: "আঞ্চলিক মেডিকেল সেন্টার",
      address: "২৫ মেডিকেল এভিনিউ, যেকোনো শহর",
      contactNumber: "৫৫৫-২০০-৩০০০",
      imageUrl:
        "https://i.ibb.co.com/9HxGn3C1/Gemini-Generated-Image-tdpa5etdpa5etdpa.jpg",
      website: "www.regionalmedicalcenter.com", // Added website address
    },
    doctor: {
      doctorId: "DR-13579",
      firstName: "এমিলি",
      lastName: "ডেভিস",
      specialization: "ডার্মাটোলজি",
    },
    appointmentDate: "২০২৩-১১-১৬",
    appointmentTime: "১৪:৩০",
    location: "ডার্মাটোলজি ক্লিনিক, ৩য় তলা",
    reasonForVisit: "ত্বকের ফুসকুড়ি মূল্যায়ন",
    notes: "অ্যাপয়েন্টমেন্টের আগে লোশন বা ক্রিম লাগানো এড়িয়ে চলুন।",
    fees: {
      amount: 2000,
      currency: "BDT",
    },
    paymentStatus: "Pending",
  },
  {
    appointmentId: "APPT-20231027-003",
    hospital: {
      hospitalId: "HOSP-003",
      hospitalName: "সেন্ট লুকস হাসপাতাল",
      address: "৪০ চার্চ স্ট্রিট, যেকোনো শহর",
      contactNumber: "৫৫৫-৩০০-৪০০০",
      imageUrl:
        "https://i.ibb.co.com/MD6vQsts/Gemini-Generated-Image-4gg28v4gg28v4gg2.jpg",
      website: "www.stlukeshospital.com", // Added website address
    },
    doctor: {
      doctorId: "DR-24680",
      firstName: "মাইকেল",
      lastName: "উইলসন",
      specialization: "পেডিয়াট্রিক্স",
    },
    appointmentDate: "২০২৩-১১-১৭",
    appointmentTime: "০৯:১৫",
    location: "পেডিয়াট্রিক্স ক্লিনিক, ১ম তলা",
    reasonForVisit: "বার্ষিক চেকআপ",
    notes: "টিকা দেওয়ার রেকর্ড আনুন।",
    fees: {
      amount: 1200,
      currency: "BDT",
    },
    paymentStatus: "Paid",
  },
  {
    appointmentId: "APPT-20231027-004",
    hospital: {
      hospitalId: "HOSP-004",
      hospitalName: "কমিউনিটি হেলথ ক্লিনিক",
      address: "১৫ মেইন স্ট্রিট, যেকোনো শহর",
      contactNumber: "৫৫৫-৪০০-৫০০০",
      imageUrl:
        "https://i.ibb.co.com/B5xk6KBB/Gemini-Generated-Image-e7cpye7cpye7cpye.jpg",
      website: "www.communityhealthclinic.org", // Added website address
    },
    doctor: {
      doctorId: "DR-98765",
      firstName: "জেসিকা",
      lastName: "মুর",
      specialization: "অর্থোপেডিক্স",
    },
    appointmentDate: "২০২৩-১১-১৮",
    appointmentTime: "১১:০০",
    location: "অর্থোপেডিক্স ক্লিনিক, ৪র্থ তলা",
    reasonForVisit: "হাঁটু ব্যথার মূল্যায়ন",
    notes: "আরামদায়ক পোশাক পরুন।",
    fees: {
      amount: 2500,
      currency: "BDT",
    },
    paymentStatus: "Partially Paid",
  },
  {
    appointmentId: "APPT-20231027-005",
    hospital: {
      hospitalId: "HOSP-005",
      hospitalName: "স্পেশালিটি সার্জিক্যাল সেন্টার",
      address: "৩০ সার্জিক্যাল ড্রাইভ, যেকোনো শহর",
      contactNumber: "৫৫৫-৫০০-৬০০০",
      imageUrl:
        "https://i.ibb.co.com/4wTp4Jvr/Gemini-Generated-Image-aa1y5aaa1y5aaa1y.jpg",
      website: "www.specialtysurgicalcenter.com", // Added website address
    },
    doctor: {
      doctorId: "DR-36912",
      firstName: "ডেভিড",
      lastName: "টেইলর",
      specialization: "নিউরোলোজি",
    },
    appointmentDate: "২০২৩-১১-১৯",
    appointmentTime: "১৫:৪৫",
    location: "নিউরোলোজি ক্লিনিক, ৫ম তলা",
    reasonForVisit: "মাইগ্রেন মূল্যায়ন",
    notes: "সাম্প্রতিক মাথাব্যথার একটি লগ রাখুন।",
    fees: {
      amount: 3000,
      currency: "BDT",
    },
    paymentStatus: "Not Paid",
  },
  {
    appointmentId: "APPT-20231028-006",
    hospital: {
      hospitalId: "HOSP-001",
      hospitalName: "সিটি জেনারেল হাসপাতাল",
      address: "১০ হাসপাতাল রোড, যেকোনো শহর",
      contactNumber: "৫৫৫-১০০-২০০০",
      imageUrl:
        "https://i.ibb.co.com/ym6QDhww/Gemini-Generated-Image-a31u5na31u5na31u.jpg",
      website: "www.citygeneralhospital.com", // Added website address
    },
    doctor: {
      doctorId: "DR-11223",
      firstName: "সোফিয়া",
      lastName: "রহমান",
      specialization: "গাইনোকোলজি",
    },
    appointmentDate: "২০২৩-১১-২০",
    appointmentTime: "১২:০০",
    location: "গাইনোকোলজি ক্লিনিক, ৬ষ্ঠ তলা",
    reasonForVisit: "প্রসবপূর্ব চেকআপ",
    notes: "আল্ট্রাসাউন্ড রিপোর্ট আনুন।",
    fees: {
      amount: 2800,
      currency: "BDT",
    },
    paymentStatus: "Paid",
  },
  {
    appointmentId: "APPT-20231028-007",
    hospital: {
      hospitalId: "HOSP-002",
      hospitalName: "আঞ্চলিক মেডিকেল সেন্টার",
      address: "২৫ মেডিকেল এভিনিউ, যেকোনো শহর",
      contactNumber: "৫৫৫-২০০-৩০০০",
      imageUrl:
        "https://i.ibb.co.com/9HxGn3C1/Gemini-Generated-Image-tdpa5etdpa5etdpa.jpg",
      website: "www.regionalmedicalcenter.com", // Added website address
    },
    doctor: {
      doctorId: "DR-44556",
      firstName: "আরিফ",
      lastName: "হোসেন",
      specialization: "ইউরোলজি",
    },
    appointmentDate: "২০২৩-১১-২১",
    appointmentTime: "১৪:৪৫",
    location: "ইউরোলজি ক্লিনিক, ৭ম তলা",
    reasonForVisit: "কিডনি স্টোন চেকআপ",
    notes: "রক্ত ও ইউরিন টেস্ট রিপোর্ট আনুন।",
    fees: {
      amount: 3200,
      currency: "BDT",
    },
    paymentStatus: "Pending",
  },
  {
    appointmentId: "APPT-20231028-008",
    hospital: {
      hospitalId: "HOSP-003",
      hospitalName: "সেন্ট লুকস হাসপাতাল",
      address: "৪০ চার্চ স্ট্রিট, যেকোনো শহর",
      contactNumber: "৫৫৫-৩০০-৪০০০",
      imageUrl:
        "https://i.ibb.co.com/MD6vQsts/Gemini-Generated-Image-4gg28v4gg28v4gg2.jpg",
      website: "www.stlukeshospital.com", // Added website address
    },
    doctor: {
      doctorId: "DR-77889",
      firstName: "ফারজানা",
      lastName: "আক্তার",
      specialization: "অপথালমোলজি",
    },
    appointmentDate: "২০২৩-১১-২২",
    appointmentTime: "১০:৩০",
    location: "অপথালমোলজি ক্লিনিক, ৮ম তলা",
    reasonForVisit: "চোখের সাধারণ চেকআপ",
    notes: "চোখের চশমার প্রেসক্রিপশন আনুন।",
    fees: {
      amount: 1800,
      currency: "BDT",
    },
    paymentStatus: "Paid",
  },
  {
    appointmentId: "APPT-20231028-009",
    hospital: {
      hospitalId: "HOSP-004",
      hospitalName: "কমিউনিটি হেলথ ক্লিনিক",
      address: "১৫ মেইন স্ট্রিট, যেকোনো শহর",
      contactNumber: "৫৫৫-৪০০-৫০০০",
      imageUrl:
        "https://i.ibb.co.com/B5xk6KBB/Gemini-Generated-Image-e7cpye7cpye7cpye.jpg",
      website: "www.communityhealthclinic.org", // Added website address
    },
    doctor: {
      doctorId: "DR-99001",
      firstName: "ইমরান",
      lastName: "কবির",
      specialization: "ইএনটি",
    },
    appointmentDate: "২০২৩-১১-২৩",
    appointmentTime: "১১:৪৫",
    location: "ইএনটি ক্লিনিক, ৯ম তলা",
    reasonForVisit: "নাক ও গলার সমস্যা",
    notes: "পূর্বের কোনো টেস্ট রিপোর্ট থাকলে আনুন।",
    fees: {
      amount: 2200,
      currency: "BDT",
    },
    paymentStatus: "Partially Paid",
  },
  {
    appointmentId: "APPT-20231028-010",
    hospital: {
      hospitalId: "HOSP-005",
      hospitalName: "স্পেশালিটি সার্জিক্যাল সেন্টার",
      address: "৩০ সার্জিক্যাল ড্রাইভ, যেকোনো শহর",
      contactNumber: "৫৫৫-৫০০-৬০০০",
      imageUrl:
        "https://i.ibb.co.com/4wTp4Jvr/Gemini-Generated-Image-aa1y5aaa1y5aaa1y.jpg",
      website: "www.specialtysurgicalcenter.com", // Added website address
    },
    doctor: {
      doctorId: "DR-22334",
      firstName: "সাদিয়া",
      lastName: "আহমেদ",
      specialization: "প্লাস্টিক সার্জারি",
    },
    appointmentDate: "২০২৩-১১-২৪",
    appointmentTime: "১৫:৩০",
    location: "প্লাস্টিক সার্জারি ক্লিনিক, ১০ম তলা",
    reasonForVisit: "পোড়া দাগের চিকিৎসা",
    notes: "পূর্বের চিকিৎসার ছবি আনুন।",
    fees: {
      amount: 3500,
      currency: "BDT",
    },
    paymentStatus: "Not Paid",
  },
];


export {hospitalData , doctorData}
